# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Configs::Discord`.
# Please instead update this file by running `bin/tapioca dsl Configs::Discord`.


class Configs::Discord
  class << self
    sig { returns(T.untyped) }
    def bot_token; end

    sig { returns(T.untyped) }
    def client_id; end

    sig { returns(T.untyped) }
    def client_secret; end
  end
end
