# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `climate_control` gem.
# Please instead update this file by running `bin/tapioca gem climate_control`.


# pkg:gem/climate_control#lib/climate_control/errors.rb:1
module ClimateControl
  extend ::ClimateControl
  extend ::Gem::Deprecate

  # pkg:gem/climate_control#lib/climate_control.rb:60
  def _deprecated_env; end

  # pkg:gem/climate_control#lib/climate_control.rb:56
  def env(*args, **_arg1, &block); end

  # pkg:gem/climate_control#lib/climate_control.rb:12
  def modify(environment_overrides = T.unsafe(nil), &block); end

  # pkg:gem/climate_control#lib/climate_control.rb:35
  def unsafe_modify(environment_overrides = T.unsafe(nil), &block); end

  private

  # pkg:gem/climate_control#lib/climate_control.rb:64
  def copy(overrides); end
end

# pkg:gem/climate_control#lib/climate_control.rb:9
ClimateControl::SEMAPHORE = T.let(T.unsafe(nil), Monitor)

# pkg:gem/climate_control#lib/climate_control/errors.rb:2
class ClimateControl::UnassignableValueError < ::ArgumentError; end

# pkg:gem/climate_control#lib/climate_control/version.rb:2
ClimateControl::VERSION = T.let(T.unsafe(nil), String)
