# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `dry-operation` gem.
# Please instead update this file by running `bin/tapioca gem dry-operation`.


# pkg:gem/dry-operation#lib/dry/operation/errors.rb:3
module Dry; end

# DSL for chaining operations that can fail
#
# {Dry::Operation} is a thin DSL wrapping dry-monads that allows you to chain
# operations by focusing on the happy path and short-circuiting on failure.
#
# The canonical way of using it is to subclass {Dry::Operation} and define
# your flow in the `#call` method. Individual operations can be called with
# {#step}. They need to return either a success or a failure result.
# Successful results will be automatically unwrapped, while a failure will
# stop further execution of the method.
#
# ```ruby
# class MyOperation < Dry::Operation
#   def call(input)
#     attrs = step validate(input)
#     user = step persist(attrs)
#     step notify(user)
#     user
#   end
#
#   def validate(input)
#    # Dry::Monads::Result::Success or Dry::Monads::Result::Failure
#   end
#
#   def persist(attrs)
#    # Dry::Monads::Result::Success or Dry::Monads::Result::Failure
#   end
#
#   def notify(user)
#    # Dry::Monads::Result::Success or Dry::Monads::Result::Failure
#   end
# end
#
# include Dry::Monads[:result]
#
# case MyOperation.new.call(input)
# in Success(user)
#   puts "User #{user.name} created"
# in Failure[:invalid_input, validation_errors]
#   puts "Invalid input: #{validation_errors}"
# in Failure(:database_error)
#   puts "Database error"
# in Failure(:email_error)
#   puts "Email error"
# end
# ```
#
# Under the hood, the `#call` method is decorated to allow skipping the rest
# of its execution when a failure is encountered. You can choose to use another
# method with {ClassContext#operate_on} (which also accepts a list of methods):
#
# ```ruby
# class MyOperation < Dry::Operation
#   operate_on :run # or operate_on :run, :call
#
#   def run(input)
#     attrs = step validate(input)
#     user = step persist(attrs)
#     step notify(user)
#     user
#   end
#
#   # ...
# end
# ```
#
# As you can see, the aforementioned behavior allows you to write your flow
# in a linear fashion. Failures are mostly handled locally by each individual
# operation. However, you can also define a global failure handler by defining
# an `#on_failure` method. It will be called with the wrapped failure value
# and, in the case of accepting a second argument, the name of the method that
# defined the flow:
#
# ```ruby
# class MyOperation < Dry::Operation
#   def call(input)
#     attrs = step validate(input)
#     user = step persist(attrs)
#     step notify(user)
#     user
#   end
#
#   def on_failure(user) # or def on_failure(failure_value, method_name)
#     log_failure(user)
#   end
# end
# ```
#
# You can opt out altogether of this behavior via {ClassContext#skip_prepending}. If so,
# you manually need to wrap your flow within the {#steps} method and manually
# handle global failures.
#
# ```ruby
# class MyOperation < Dry::Operation
#   skip_prepending
#
#   def call(input)
#     steps do
#       attrs = step validate(input)
#       user = step persist(attrs)
#       step notify(user)
#       user
#     end.tap do |result|
#       log_failure(result.failure) if result.failure?
#     end
#   end
#
#   # ...
# end
# ```
#
# The behavior configured by {ClassContext#operate_on} and {ClassContext#skip_prepending} is
# inherited by subclasses.
#
# Some extensions are available under the `Dry::Operation::Extensions`
# namespace, providing additional functionality that can be included in your
# operation classes.
#
# pkg:gem/dry-operation#lib/dry/operation/errors.rb:4
class Dry::Operation
  include ::Dry::Monads::Result::Mixin::Constructors
  include ::Dry::Monads::Result::Mixin
  extend ::Dry::Operation::ClassContext

  # Invokes a callable in case of block's failure
  #
  # This method is useful when you want to perform some side-effect when a
  # failure is encountered. It's meant to be used within the {#steps} block
  # commonly wrapping a sub-set of {#step} calls.
  #
  # @param handler [#call] a callable that will be called with the encountered failure.
  #   By default, it throws `FAILURE_TAG` with the failure.
  # @yieldreturn [Object]
  # @return [Object] the block's return value when it's not a failure or the handler's
  #   return value when the block returns a failure
  #
  # pkg:gem/dry-operation#lib/dry/operation.rb:184
  def intercepting_failure(handler = T.unsafe(nil), &block); end

  # Unwraps a {Dry::Monads::Result::Success}
  #
  # Throws `:halt` with a {Dry::Monads::Result::Failure} on failure.
  #
  # @param result [Dry::Monads::Result]
  # @return [Object] wrapped value
  # @see #steps
  #
  # pkg:gem/dry-operation#lib/dry/operation.rb:165
  def step(result); end

  # Wraps block's return value in a {Dry::Monads::Result::Success}
  #
  # Catches `:halt` and returns it
  #
  # @yieldreturn [Object]
  # @return [Dry::Monads::Result::Success]
  # @see #step
  #
  # pkg:gem/dry-operation#lib/dry/operation.rb:154
  def steps(&block); end

  # Throws `:halt` with a failure
  #
  # @param failure [Dry::Monads::Result::Failure]
  #
  # pkg:gem/dry-operation#lib/dry/operation.rb:198
  def throw_failure(failure); end

  private

  # pkg:gem/dry-operation#lib/dry/operation.rb:204
  def catching_failure(&block); end

  class << self
    # pkg:gem/dry-operation#lib/dry/operation.rb:126
    def loader; end
  end
end

# {Dry::Operation} class context
#
# pkg:gem/dry-operation#lib/dry/operation/class_context.rb:6
module Dry::Operation::ClassContext
  # @api private
  #
  # pkg:gem/dry-operation#lib/dry/operation/class_context.rb:36
  def inherited(klass); end

  # Configures the instance methods to be prepended
  #
  # The given methods will be prepended with a wrapper that calls {#steps}
  # before calling the original method.
  #
  # This method must be called before defining any of the methods to be
  # prepended or before prepending any other method.
  #
  # @param methods [Array<Symbol>] methods to prepend
  # @raise [MethodsToPrependAlreadyDefinedError] if any of the methods have
  #  already been defined in self
  # @raise [PrependConfigurationError] if there's already a prepended method
  #
  # pkg:gem/dry-operation#lib/dry/operation/class_context.rb:22
  def operate_on(*methods); end

  # Skips prepending any method
  #
  # This method must be called before any method is prepended.
  #
  # @raise [PrependConfigurationError] if there's already a prepended method
  #
  # pkg:gem/dry-operation#lib/dry/operation/class_context.rb:31
  def skip_prepending; end

  class << self
    # @api private
    #
    # pkg:gem/dry-operation#lib/dry/operation/class_context.rb:46
    def directly_inherited(klass); end

    # @api private
    #
    # pkg:gem/dry-operation#lib/dry/operation/class_context.rb:55
    def indirectly_inherited(klass); end
  end
end

# Default methods to be prepended unless changed via {.operate_on}
#
# pkg:gem/dry-operation#lib/dry/operation/class_context.rb:8
Dry::Operation::ClassContext::DEFAULT_METHODS_TO_PREPEND = T.let(T.unsafe(nil), Array)

# @api private
#
# pkg:gem/dry-operation#lib/dry/operation/class_context.rb:63
module Dry::Operation::ClassContext::MethodAddedHook
  # pkg:gem/dry-operation#lib/dry/operation/class_context.rb:64
  def method_added(method); end
end

# @api private
#
# pkg:gem/dry-operation#lib/dry/operation/class_context/prepend_manager.rb:9
class Dry::Operation::ClassContext::PrependManager
  # pkg:gem/dry-operation#lib/dry/operation/class_context/prepend_manager.rb:10
  def initialize(klass:, methods_to_prepend:, prepended_methods: T.unsafe(nil)); end

  # pkg:gem/dry-operation#lib/dry/operation/class_context/prepend_manager.rb:33
  def call(method:); end

  # pkg:gem/dry-operation#lib/dry/operation/class_context/prepend_manager.rb:40
  def for_subclass(subclass); end

  # pkg:gem/dry-operation#lib/dry/operation/class_context/prepend_manager.rb:16
  def register(*methods); end

  # pkg:gem/dry-operation#lib/dry/operation/class_context/prepend_manager.rb:27
  def void; end

  private

  # pkg:gem/dry-operation#lib/dry/operation/class_context/prepend_manager.rb:50
  def ensure_pristine; end
end

# @api private
#
# pkg:gem/dry-operation#lib/dry/operation/class_context/steps_method_prepender.rb:9
class Dry::Operation::ClassContext::StepsMethodPrepender < ::Module
  # pkg:gem/dry-operation#lib/dry/operation/class_context/steps_method_prepender.rb:29
  def initialize(method:, result_handler: T.unsafe(nil)); end

  # pkg:gem/dry-operation#lib/dry/operation/class_context/steps_method_prepender.rb:35
  def included(klass); end

  private

  # pkg:gem/dry-operation#lib/dry/operation/class_context/steps_method_prepender.rb:41
  def mod; end
end

# pkg:gem/dry-operation#lib/dry/operation/class_context/steps_method_prepender.rb:10
Dry::Operation::ClassContext::StepsMethodPrepender::FAILURE_HOOK_METHOD_NAME = T.let(T.unsafe(nil), Symbol)

# pkg:gem/dry-operation#lib/dry/operation/class_context/steps_method_prepender.rb:12
Dry::Operation::ClassContext::StepsMethodPrepender::RESULT_HANDLER = T.let(T.unsafe(nil), Proc)

# pkg:gem/dry-operation#lib/dry/operation/errors.rb:5
class Dry::Operation::Error < ::StandardError; end

# An error related to an extension
#
# pkg:gem/dry-operation#lib/dry/operation/errors.rb:48
class Dry::Operation::ExtensionError < ::StandardError; end

# pkg:gem/dry-operation#lib/dry/operation.rb:141
Dry::Operation::FAILURE_TAG = T.let(T.unsafe(nil), Symbol)

# Defined failure hook has wrong arity
#
# pkg:gem/dry-operation#lib/dry/operation/errors.rb:51
class Dry::Operation::FailureHookArityError < ::StandardError
  # pkg:gem/dry-operation#lib/dry/operation/errors.rb:52
  def initialize(hook:); end
end

# pkg:gem/dry-operation#lib/dry/operation/errors.rb:38
class Dry::Operation::InvalidStepResultError < ::Dry::Operation::Error
  # pkg:gem/dry-operation#lib/dry/operation/errors.rb:39
  def initialize(result:); end
end

# Methods to prepend have already been defined
#
# pkg:gem/dry-operation#lib/dry/operation/errors.rb:8
class Dry::Operation::MethodsToPrependAlreadyDefinedError < ::Dry::Operation::Error
  # pkg:gem/dry-operation#lib/dry/operation/errors.rb:9
  def initialize(methods:); end
end

# Missing dependency required by an extension
#
# pkg:gem/dry-operation#lib/dry/operation/errors.rb:29
class Dry::Operation::MissingDependencyError < ::Dry::Operation::Error
  # pkg:gem/dry-operation#lib/dry/operation/errors.rb:30
  def initialize(gem:, extension:); end
end

# Configuring prepending after a method has already been prepended
#
# pkg:gem/dry-operation#lib/dry/operation/errors.rb:18
class Dry::Operation::PrependConfigurationError < ::Dry::Operation::Error
  # pkg:gem/dry-operation#lib/dry/operation/errors.rb:19
  def initialize(methods:); end
end

# pkg:gem/dry-operation#lib/dry/operation/version.rb:5
Dry::Operation::VERSION = T.let(T.unsafe(nil), String)
