# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `groupdate` gem.
# Please instead update this file by running `bin/tapioca gem groupdate`.


class ActiveRecord::Base
  include ::ActiveModel::ForbiddenAttributesProtection
  include ::ActiveModel::AttributeAssignment
  include ::ActiveModel::Access
  include ::ActiveModel::Serialization
  extend ::Groupdate::QueryMethods
  extend ::ActiveRecord::SignedId::DeprecateSignedIdVerifierSecret
end

class ActiveRecord::Relation
  include ::ActiveModel::ForbiddenAttributesProtection
  include ::Groupdate::Relation
end

# pkg:gem/groupdate#lib/groupdate/enumerable.rb:1
module Enumerable
  extend ::ActiveSupport::EnumerableCoreExt::Constants

  # pkg:gem/groupdate#lib/groupdate/enumerable.rb:3
  def group_by_day(*args, **options, &block); end

  # pkg:gem/groupdate#lib/groupdate/enumerable.rb:3
  def group_by_day_of_month(*args, **options, &block); end

  # pkg:gem/groupdate#lib/groupdate/enumerable.rb:3
  def group_by_day_of_week(*args, **options, &block); end

  # pkg:gem/groupdate#lib/groupdate/enumerable.rb:3
  def group_by_day_of_year(*args, **options, &block); end

  # pkg:gem/groupdate#lib/groupdate/enumerable.rb:3
  def group_by_hour(*args, **options, &block); end

  # pkg:gem/groupdate#lib/groupdate/enumerable.rb:3
  def group_by_hour_of_day(*args, **options, &block); end

  # pkg:gem/groupdate#lib/groupdate/enumerable.rb:3
  def group_by_minute(*args, **options, &block); end

  # pkg:gem/groupdate#lib/groupdate/enumerable.rb:3
  def group_by_minute_of_hour(*args, **options, &block); end

  # pkg:gem/groupdate#lib/groupdate/enumerable.rb:3
  def group_by_month(*args, **options, &block); end

  # pkg:gem/groupdate#lib/groupdate/enumerable.rb:3
  def group_by_month_of_year(*args, **options, &block); end

  # pkg:gem/groupdate#lib/groupdate/enumerable.rb:15
  def group_by_period(period, *args, **options, &block); end

  # pkg:gem/groupdate#lib/groupdate/enumerable.rb:3
  def group_by_quarter(*args, **options, &block); end

  # pkg:gem/groupdate#lib/groupdate/enumerable.rb:3
  def group_by_second(*args, **options, &block); end

  # pkg:gem/groupdate#lib/groupdate/enumerable.rb:3
  def group_by_week(*args, **options, &block); end

  # pkg:gem/groupdate#lib/groupdate/enumerable.rb:3
  def group_by_year(*args, **options, &block); end
end

# pkg:gem/groupdate#lib/groupdate/magic.rb:3
module Groupdate
  # pkg:gem/groupdate#lib/groupdate.rb:23
  def day_start; end

  # pkg:gem/groupdate#lib/groupdate.rb:23
  def day_start=(val); end

  # pkg:gem/groupdate#lib/groupdate.rb:23
  def time_zone; end

  # pkg:gem/groupdate#lib/groupdate.rb:23
  def time_zone=(val); end

  # pkg:gem/groupdate#lib/groupdate.rb:23
  def week_start; end

  # pkg:gem/groupdate#lib/groupdate.rb:23
  def week_start=(val); end

  class << self
    # pkg:gem/groupdate#lib/groupdate.rb:35
    def adapters; end

    # pkg:gem/groupdate#lib/groupdate.rb:23
    def day_start; end

    # pkg:gem/groupdate#lib/groupdate.rb:23
    def day_start=(val); end

    # api for gems like ActiveMedian
    #
    # pkg:gem/groupdate#lib/groupdate.rb:28
    def process_result(relation, result, **options); end

    # pkg:gem/groupdate#lib/groupdate.rb:39
    def register_adapter(name, adapter); end

    # pkg:gem/groupdate#lib/groupdate.rb:23
    def time_zone; end

    # pkg:gem/groupdate#lib/groupdate.rb:23
    def time_zone=(val); end

    # pkg:gem/groupdate#lib/groupdate.rb:23
    def week_start; end

    # pkg:gem/groupdate#lib/groupdate.rb:23
    def week_start=(val); end
  end
end

# pkg:gem/groupdate#lib/groupdate/adapters/base_adapter.rb:2
module Groupdate::Adapters; end

# pkg:gem/groupdate#lib/groupdate/adapters/base_adapter.rb:3
class Groupdate::Adapters::BaseAdapter
  # pkg:gem/groupdate#lib/groupdate/adapters/base_adapter.rb:6
  def initialize(relation, column:, period:, time_zone:, time_range:, week_start:, day_start:, n_seconds:, adapter_name: T.unsafe(nil)); end

  # pkg:gem/groupdate#lib/groupdate/adapters/base_adapter.rb:4
  def column; end

  # pkg:gem/groupdate#lib/groupdate/adapters/base_adapter.rb:4
  def day_start; end

  # pkg:gem/groupdate#lib/groupdate/adapters/base_adapter.rb:22
  def generate; end

  # pkg:gem/groupdate#lib/groupdate/adapters/base_adapter.rb:4
  def n_seconds; end

  # pkg:gem/groupdate#lib/groupdate/adapters/base_adapter.rb:4
  def period; end

  # pkg:gem/groupdate#lib/groupdate/adapters/base_adapter.rb:4
  def week_start; end

  private

  # pkg:gem/groupdate#lib/groupdate/adapters/base_adapter.rb:28
  def where_clause; end
end

# pkg:gem/groupdate#lib/groupdate/adapters/mysql_adapter.rb:3
class Groupdate::Adapters::MySQLAdapter < ::Groupdate::Adapters::BaseAdapter
  # pkg:gem/groupdate#lib/groupdate/adapters/mysql_adapter.rb:57
  def clean_group_clause(clause); end

  # pkg:gem/groupdate#lib/groupdate/adapters/mysql_adapter.rb:4
  def group_clause; end
end

# pkg:gem/groupdate#lib/groupdate/adapters/postgresql_adapter.rb:3
class Groupdate::Adapters::PostgreSQLAdapter < ::Groupdate::Adapters::BaseAdapter
  # pkg:gem/groupdate#lib/groupdate/adapters/postgresql_adapter.rb:41
  def clean_group_clause(clause); end

  # pkg:gem/groupdate#lib/groupdate/adapters/postgresql_adapter.rb:4
  def group_clause; end
end

# pkg:gem/groupdate#lib/groupdate/adapters/sqlite_adapter.rb:3
class Groupdate::Adapters::SQLiteAdapter < ::Groupdate::Adapters::BaseAdapter
  # pkg:gem/groupdate#lib/groupdate/adapters/sqlite_adapter.rb:4
  def group_clause; end

  private

  # pkg:gem/groupdate#lib/groupdate/adapters/sqlite_adapter.rb:55
  def setup_function; end
end

# pkg:gem/groupdate#lib/groupdate.rb:18
class Groupdate::Error < ::RuntimeError; end

# pkg:gem/groupdate#lib/groupdate.rb:21
Groupdate::METHODS = T.let(T.unsafe(nil), Array)

# pkg:gem/groupdate#lib/groupdate/magic.rb:4
class Groupdate::Magic
  # pkg:gem/groupdate#lib/groupdate/magic.rb:9
  def initialize(period:, **options); end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:68
  def day_start; end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:7
  def group_index; end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:7
  def group_index=(_arg0); end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:7
  def n_seconds; end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:7
  def n_seconds=(_arg0); end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:7
  def options; end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:7
  def options=(_arg0); end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:7
  def period; end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:7
  def period=(_arg0); end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:72
  def range; end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:84
  def series_builder; end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:97
  def time_range; end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:53
  def time_zone; end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:46
  def validate_arguments; end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:24
  def validate_keywords; end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:61
  def week_start; end

  class << self
    # pkg:gem/groupdate#lib/groupdate/magic.rb:101
    def validate_period(period, permit); end
  end
end

# pkg:gem/groupdate#lib/groupdate/magic.rb:5
Groupdate::Magic::DAYS = T.let(T.unsafe(nil), Array)

# pkg:gem/groupdate#lib/groupdate/magic.rb:106
class Groupdate::Magic::Enumerable < ::Groupdate::Magic
  # pkg:gem/groupdate#lib/groupdate/magic.rb:107
  def group_by(enum, &_block); end

  class << self
    # pkg:gem/groupdate#lib/groupdate/magic.rb:116
    def group_by(enum, period, options, &block); end
  end
end

# pkg:gem/groupdate#lib/groupdate/magic.rb:121
class Groupdate::Magic::Relation < ::Groupdate::Magic
  # pkg:gem/groupdate#lib/groupdate/magic.rb:122
  def initialize(**options); end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:145
  def cast_method; end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:169
  def cast_result(result, multiple_groups); end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:193
  def check_nils(result, multiple_groups, relation); end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:127
  def perform(relation, result, default_value:); end

  # pkg:gem/groupdate#lib/groupdate/magic.rb:182
  def time_zone_support?(relation); end

  class << self
    # pkg:gem/groupdate#lib/groupdate/magic.rb:204
    def generate_relation(relation, field:, **options); end

    # allow any options to keep flexible for future
    #
    # pkg:gem/groupdate#lib/groupdate/magic.rb:261
    def process_result(relation, result, **options); end

    # resolves eagerly
    # need to convert both where_clause (easy)
    # and group_clause (not easy) if want to avoid this
    #
    # pkg:gem/groupdate#lib/groupdate/magic.rb:253
    def resolve_column(relation, column); end

    # basic version of Active Record disallow_raw_sql!
    # symbol = column (safe), Arel node = SQL (safe), other = untrusted
    # matches table.column and column
    #
    # pkg:gem/groupdate#lib/groupdate/magic.rb:240
    def validate_column(column); end
  end
end

# pkg:gem/groupdate#lib/groupdate.rb:20
Groupdate::PERIODS = T.let(T.unsafe(nil), Array)

# pkg:gem/groupdate#lib/groupdate/query_methods.rb:2
module Groupdate::QueryMethods
  # pkg:gem/groupdate#lib/groupdate/query_methods.rb:4
  def group_by_day(field, **options); end

  # pkg:gem/groupdate#lib/groupdate/query_methods.rb:4
  def group_by_day_of_month(field, **options); end

  # pkg:gem/groupdate#lib/groupdate/query_methods.rb:4
  def group_by_day_of_week(field, **options); end

  # pkg:gem/groupdate#lib/groupdate/query_methods.rb:4
  def group_by_day_of_year(field, **options); end

  # pkg:gem/groupdate#lib/groupdate/query_methods.rb:4
  def group_by_hour(field, **options); end

  # pkg:gem/groupdate#lib/groupdate/query_methods.rb:4
  def group_by_hour_of_day(field, **options); end

  # pkg:gem/groupdate#lib/groupdate/query_methods.rb:4
  def group_by_minute(field, **options); end

  # pkg:gem/groupdate#lib/groupdate/query_methods.rb:4
  def group_by_minute_of_hour(field, **options); end

  # pkg:gem/groupdate#lib/groupdate/query_methods.rb:4
  def group_by_month(field, **options); end

  # pkg:gem/groupdate#lib/groupdate/query_methods.rb:4
  def group_by_month_of_year(field, **options); end

  # pkg:gem/groupdate#lib/groupdate/query_methods.rb:13
  def group_by_period(period, field, permit: T.unsafe(nil), **options); end

  # pkg:gem/groupdate#lib/groupdate/query_methods.rb:4
  def group_by_quarter(field, **options); end

  # pkg:gem/groupdate#lib/groupdate/query_methods.rb:4
  def group_by_second(field, **options); end

  # pkg:gem/groupdate#lib/groupdate/query_methods.rb:4
  def group_by_week(field, **options); end

  # pkg:gem/groupdate#lib/groupdate/query_methods.rb:4
  def group_by_year(field, **options); end
end

# pkg:gem/groupdate#lib/groupdate/relation.rb:4
module Groupdate::Relation
  extend ::ActiveSupport::Concern

  # pkg:gem/groupdate#lib/groupdate/relation.rb:11
  def calculate(*args, &block); end
end

# pkg:gem/groupdate#lib/groupdate/series_builder.rb:2
class Groupdate::SeriesBuilder
  # pkg:gem/groupdate#lib/groupdate/series_builder.rb:5
  def initialize(period:, time_zone:, day_start:, week_start:, n_seconds:, **options); end

  # pkg:gem/groupdate#lib/groupdate/series_builder.rb:3
  def day_start; end

  # pkg:gem/groupdate#lib/groupdate/series_builder.rb:15
  def generate(data, default_value:, series_default: T.unsafe(nil), multiple_groups: T.unsafe(nil), group_index: T.unsafe(nil)); end

  # pkg:gem/groupdate#lib/groupdate/series_builder.rb:3
  def n_seconds; end

  # pkg:gem/groupdate#lib/groupdate/series_builder.rb:3
  def options; end

  # pkg:gem/groupdate#lib/groupdate/series_builder.rb:3
  def period; end

  # pkg:gem/groupdate#lib/groupdate/series_builder.rb:44
  def round_time(time); end

  # pkg:gem/groupdate#lib/groupdate/series_builder.rb:104
  def time_range; end

  # pkg:gem/groupdate#lib/groupdate/series_builder.rb:3
  def time_zone; end

  # pkg:gem/groupdate#lib/groupdate/series_builder.rb:3
  def week_start; end

  private

  # pkg:gem/groupdate#lib/groupdate/series_builder.rb:301
  def entire_series?(series_default); end

  # pkg:gem/groupdate#lib/groupdate/series_builder.rb:168
  def generate_series(data, multiple_groups, group_index); end

  # pkg:gem/groupdate#lib/groupdate/series_builder.rb:285
  def handle_multiple(data, series, multiple_groups, group_index); end

  # pkg:gem/groupdate#lib/groupdate/series_builder.rb:242
  def key_format; end

  # pkg:gem/groupdate#lib/groupdate/series_builder.rb:164
  def now; end

  # pkg:gem/groupdate#lib/groupdate/series_builder.rb:275
  def step; end

  class << self
    # pkg:gem/groupdate#lib/groupdate/series_builder.rb:53
    def round_time(time, period, time_zone, day_start, week_start_key); end

    # pkg:gem/groupdate#lib/groupdate/series_builder.rb:305
    def utc; end
  end
end

# pkg:gem/groupdate#lib/groupdate/version.rb:2
Groupdate::VERSION = T.let(T.unsafe(nil), String)
