# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `neighbor` gem.
# Please instead update this file by running `bin/tapioca gem neighbor`.


# pkg:gem/neighbor#lib/neighbor/mysql.rb:1
module Neighbor; end

# pkg:gem/neighbor#lib/neighbor/attribute.rb:2
class Neighbor::Attribute < ::ActiveModel::Type::Value
  # pkg:gem/neighbor#lib/neighbor/attribute.rb:5
  def initialize(cast_type:, model:, type:, attribute_name:); end

  # pkg:gem/neighbor#lib/neighbor/attribute.rb:3
  def cast(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/neighbor#lib/neighbor/attribute.rb:3
  def deserialize(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/neighbor#lib/neighbor/attribute.rb:3
  def serialize(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/neighbor#lib/neighbor/attribute.rb:3
  def type(*_arg0, **_arg1, &_arg2); end

  private

  # pkg:gem/neighbor#lib/neighbor/attribute.rb:14
  def cast_value(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/neighbor#lib/neighbor/attribute.rb:18
  def new_cast_type; end
end

# pkg:gem/neighbor#lib/neighbor.rb:16
class Neighbor::Error < ::StandardError; end

# pkg:gem/neighbor#lib/neighbor/railtie.rb:11
module Neighbor::GeneratedAttribute
  # pkg:gem/neighbor#lib/neighbor/railtie.rb:12
  def parse_type_and_options(type, *_arg1, **_arg2); end
end

# pkg:gem/neighbor#lib/neighbor/model.rb:2
module Neighbor::Model
  # pkg:gem/neighbor#lib/neighbor/model.rb:3
  def has_neighbors(*attribute_names, dimensions: T.unsafe(nil), normalize: T.unsafe(nil), type: T.unsafe(nil)); end
end

# pkg:gem/neighbor#lib/neighbor/mysql.rb:2
module Neighbor::MySQL
  class << self
    # pkg:gem/neighbor#lib/neighbor/mysql.rb:3
    def initialize!; end
  end
end

# pkg:gem/neighbor#lib/neighbor/mysql.rb:20
module Neighbor::MySQL::RegisterTypes
  # pkg:gem/neighbor#lib/neighbor/mysql.rb:21
  def initialize_type_map(m); end

  # pkg:gem/neighbor#lib/neighbor/mysql.rb:26
  def register_vector_type(m); end
end

# pkg:gem/neighbor#lib/neighbor/normalized_attribute.rb:2
class Neighbor::NormalizedAttribute < ::ActiveModel::Type::Value
  # pkg:gem/neighbor#lib/neighbor/normalized_attribute.rb:5
  def initialize(cast_type:, model:, attribute_name:); end

  # pkg:gem/neighbor#lib/neighbor/normalized_attribute.rb:11
  def cast(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/neighbor#lib/neighbor/normalized_attribute.rb:3
  def deserialize(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/neighbor#lib/neighbor/normalized_attribute.rb:3
  def serialize(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/neighbor#lib/neighbor/normalized_attribute.rb:3
  def type(*_arg0, **_arg1, &_arg2); end

  private

  # pkg:gem/neighbor#lib/neighbor/normalized_attribute.rb:17
  def cast_value(*_arg0, **_arg1, &_arg2); end
end

# pkg:gem/neighbor#lib/neighbor/postgresql.rb:2
module Neighbor::PostgreSQL
  class << self
    # pkg:gem/neighbor#lib/neighbor/postgresql.rb:3
    def initialize!; end
  end
end

# pkg:gem/neighbor#lib/neighbor/postgresql.rb:48
module Neighbor::PostgreSQL::ArrayMethods
  # pkg:gem/neighbor#lib/neighbor/postgresql.rb:49
  def type_cast_array(value, method, *_arg2, **_arg3, &_arg4); end
end

# pkg:gem/neighbor#lib/neighbor/postgresql.rb:46
class Neighbor::PostgreSQL::ArrayWrapper < ::Struct
  # pkg:gem/neighbor#lib/neighbor/postgresql.rb:46
  def to_a; end

  # pkg:gem/neighbor#lib/neighbor/postgresql.rb:46
  def to_a=(_); end

  class << self
    # pkg:gem/neighbor#lib/neighbor/postgresql.rb:46
    def [](*_arg0); end

    # pkg:gem/neighbor#lib/neighbor/postgresql.rb:46
    def inspect; end

    # pkg:gem/neighbor#lib/neighbor/postgresql.rb:46
    def keyword_init?; end

    # pkg:gem/neighbor#lib/neighbor/postgresql.rb:46
    def members; end

    # pkg:gem/neighbor#lib/neighbor/postgresql.rb:46
    def new(*_arg0); end
  end
end

# pkg:gem/neighbor#lib/neighbor/postgresql.rb:27
module Neighbor::PostgreSQL::RegisterTypes
  # pkg:gem/neighbor#lib/neighbor/postgresql.rb:28
  def initialize_type_map(m = T.unsafe(nil)); end
end

# pkg:gem/neighbor#lib/neighbor/railtie.rb:2
class Neighbor::Railtie < ::Rails::Railtie; end

# pkg:gem/neighbor#lib/neighbor/reranking.rb:2
module Neighbor::Reranking
  class << self
    # pkg:gem/neighbor#lib/neighbor/reranking.rb:3
    def rrf(first_ranking, *rankings, k: T.unsafe(nil)); end
  end
end

# pkg:gem/neighbor#lib/neighbor/sqlite.rb:2
module Neighbor::SQLite
  class << self
    # pkg:gem/neighbor#lib/neighbor/sqlite.rb:4
    def extensions; end

    # note: this is a public API (unlike PostgreSQL and MySQL)
    #
    # pkg:gem/neighbor#lib/neighbor/sqlite.rb:8
    def initialize!(extension: T.unsafe(nil)); end

    # pkg:gem/neighbor#lib/neighbor/sqlite.rb:18
    def initialize_adapter!; end

    # pkg:gem/neighbor#lib/neighbor/sqlite.rb:36
    def setup_functions(db); end

    # pkg:gem/neighbor#lib/neighbor/sqlite.rb:32
    def sqlite_vec?; end

    # pkg:gem/neighbor#lib/neighbor/sqlite.rb:28
    def vec1?; end
  end
end

# pkg:gem/neighbor#lib/neighbor/sqlite.rb:118
module Neighbor::SQLite::InstanceMethods
  # pkg:gem/neighbor#lib/neighbor/sqlite.rb:119
  def configure_connection; end
end

# pkg:gem/neighbor#lib/neighbor/sparse_vector.rb:2
class Neighbor::SparseVector
  # pkg:gem/neighbor#lib/neighbor/sparse_vector.rb:7
  def initialize(value, dimensions = T.unsafe(nil)); end

  # pkg:gem/neighbor#lib/neighbor/sparse_vector.rb:3
  def dimensions; end

  # pkg:gem/neighbor#lib/neighbor/sparse_vector.rb:3
  def indices; end

  # pkg:gem/neighbor#lib/neighbor/sparse_vector.rb:25
  def to_a; end

  # pkg:gem/neighbor#lib/neighbor/sparse_vector.rb:21
  def to_s; end

  # pkg:gem/neighbor#lib/neighbor/sparse_vector.rb:3
  def values; end

  private

  # pkg:gem/neighbor#lib/neighbor/sparse_vector.rb:42
  def from_array(arr); end

  # pkg:gem/neighbor#lib/neighbor/sparse_vector.rb:35
  def from_hash(data, dimensions); end

  class << self
    # pkg:gem/neighbor#lib/neighbor/sparse_vector.rb:56
    def from_text(string); end

    private

    # pkg:gem/neighbor#lib/neighbor/sparse_vector.rb:70
    def from_parts(dimensions, indices, values); end
  end
end

# pkg:gem/neighbor#lib/neighbor/sparse_vector.rb:5
Neighbor::SparseVector::NO_DEFAULT = T.let(T.unsafe(nil), Object)

# pkg:gem/neighbor#lib/neighbor/type/cube.rb:2
module Neighbor::Type; end

# pkg:gem/neighbor#lib/neighbor/type/cube.rb:3
class Neighbor::Type::Cube < ::ActiveModel::Type::Value
  # pkg:gem/neighbor#lib/neighbor/type/cube.rb:8
  def serialize(value); end

  # pkg:gem/neighbor#lib/neighbor/type/cube.rb:4
  def type; end

  private

  # pkg:gem/neighbor#lib/neighbor/type/cube.rb:22
  def cast_value(value); end

  # pkg:gem/neighbor#lib/neighbor/type/cube.rb:38
  def serialize_point(value); end
end

# pkg:gem/neighbor#lib/neighbor/type/halfvec.rb:3
class Neighbor::Type::Halfvec < ::ActiveModel::Type::Value
  # pkg:gem/neighbor#lib/neighbor/type/halfvec.rb:8
  def serialize(value); end

  # pkg:gem/neighbor#lib/neighbor/type/halfvec.rb:4
  def type; end

  private

  # pkg:gem/neighbor#lib/neighbor/type/halfvec.rb:17
  def cast_value(value); end
end

# pkg:gem/neighbor#lib/neighbor/type/mysql_vector.rb:3
class Neighbor::Type::MysqlVector < ::ActiveModel::Type::Binary
  # pkg:gem/neighbor#lib/neighbor/type/mysql_vector.rb:15
  def deserialize(value); end

  # pkg:gem/neighbor#lib/neighbor/type/mysql_vector.rb:8
  def serialize(value); end

  # pkg:gem/neighbor#lib/neighbor/type/mysql_vector.rb:4
  def type; end

  private

  # pkg:gem/neighbor#lib/neighbor/type/mysql_vector.rb:22
  def cast_value(value); end
end

# pkg:gem/neighbor#lib/neighbor/type/sparsevec.rb:3
class Neighbor::Type::Sparsevec < ::ActiveModel::Type::Value
  # pkg:gem/neighbor#lib/neighbor/type/sparsevec.rb:8
  def serialize(value); end

  # pkg:gem/neighbor#lib/neighbor/type/sparsevec.rb:4
  def type; end

  private

  # pkg:gem/neighbor#lib/neighbor/type/sparsevec.rb:17
  def cast_value(value); end
end

# pkg:gem/neighbor#lib/neighbor/type/sqlite_int8_vector.rb:3
class Neighbor::Type::SqliteInt8Vector < ::ActiveModel::Type::Binary
  # pkg:gem/neighbor#lib/neighbor/type/sqlite_int8_vector.rb:11
  def deserialize(value); end

  # pkg:gem/neighbor#lib/neighbor/type/sqlite_int8_vector.rb:4
  def serialize(value); end

  private

  # pkg:gem/neighbor#lib/neighbor/type/sqlite_int8_vector.rb:18
  def cast_value(value); end
end

# pkg:gem/neighbor#lib/neighbor/type/sqlite_vector.rb:3
class Neighbor::Type::SqliteVector < ::ActiveModel::Type::Binary
  # pkg:gem/neighbor#lib/neighbor/type/sqlite_vector.rb:11
  def deserialize(value); end

  # pkg:gem/neighbor#lib/neighbor/type/sqlite_vector.rb:4
  def serialize(value); end

  private

  # pkg:gem/neighbor#lib/neighbor/type/sqlite_vector.rb:18
  def cast_value(value); end
end

# pkg:gem/neighbor#lib/neighbor/type/vector.rb:3
class Neighbor::Type::Vector < ::ActiveModel::Type::Value
  # pkg:gem/neighbor#lib/neighbor/type/vector.rb:8
  def serialize(value); end

  # pkg:gem/neighbor#lib/neighbor/type/vector.rb:4
  def type; end

  private

  # pkg:gem/neighbor#lib/neighbor/type/vector.rb:17
  def cast_value(value); end
end

# pkg:gem/neighbor#lib/neighbor/utils.rb:2
module Neighbor::Utils
  class << self
    # pkg:gem/neighbor#lib/neighbor/utils.rb:50
    def adapter(model); end

    # pkg:gem/neighbor#lib/neighbor/utils.rb:46
    def array?(value); end

    # pkg:gem/neighbor#lib/neighbor/utils.rb:33
    def normalize(value, column_info:); end

    # pkg:gem/neighbor#lib/neighbor/utils.rb:221
    def normalize_required?(adapter, column_type); end

    # pkg:gem/neighbor#lib/neighbor/utils.rb:74
    def operator(adapter, column_type, distance); end

    # pkg:gem/neighbor#lib/neighbor/utils.rb:182
    def order(adapter, type, operator, quoted_attribute, query); end

    # pkg:gem/neighbor#lib/neighbor/utils.rb:61
    def type(adapter, column_type); end

    # pkg:gem/neighbor#lib/neighbor/utils.rb:23
    def validate(value, dimensions:, type:, adapter:); end

    # pkg:gem/neighbor#lib/neighbor/utils.rb:3
    def validate_dimensions(value, type, expected, adapter); end

    # pkg:gem/neighbor#lib/neighbor/utils.rb:12
    def validate_finite(value, type); end
  end
end

# pkg:gem/neighbor#lib/neighbor/version.rb:2
Neighbor::VERSION = T.let(T.unsafe(nil), String)
