# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `phlex` gem.
# Please instead update this file by running `bin/tapioca gem phlex`.


class Object < ::BasicObject
  include ::Kernel
  include ::PP::ObjectMixin

  private

  # pkg:gem/phlex#lib/phlex.rb:72
  def 💪; end
end

# pkg:gem/phlex#lib/phlex.rb:7
module Phlex
  class << self
    # pkg:gem/phlex#lib/phlex.rb:32
    def __expand_attribute_cache__(file_path); end

    # Generate an HTML string using Phlex’ HTML DSL
    #
    # pkg:gem/phlex#lib/phlex.rb:40
    def html(&block); end

    # Generate an SVG string using Phlex’ SVG DSL
    #
    # pkg:gem/phlex#lib/phlex.rb:56
    def svg(&block); end
  end
end

# pkg:gem/phlex#lib/phlex.rb:28
Phlex::ATTRIBUTE_CACHE = T.let(T.unsafe(nil), Phlex::FIFO)

# pkg:gem/phlex#lib/phlex/errors/argument_error.rb:3
class Phlex::ArgumentError < ::ArgumentError
  include ::Phlex::Error
end

# pkg:gem/phlex#lib/phlex.rb:27
Phlex::CACHED_FILES = T.let(T.unsafe(nil), Set)

# pkg:gem/phlex#lib/phlex/csv.rb:3
class Phlex::CSV
  # pkg:gem/phlex#lib/phlex/csv.rb:12
  def initialize(collection); end

  # pkg:gem/phlex#lib/phlex/csv.rb:125
  def around_row(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/phlex#lib/phlex/csv.rb:21
  def call(buffer = T.unsafe(nil), context: T.unsafe(nil), delimiter: T.unsafe(nil)); end

  # pkg:gem/phlex#lib/phlex/csv.rb:19
  def collection; end

  # pkg:gem/phlex#lib/phlex/csv.rb:134
  def content_type; end

  # pkg:gem/phlex#lib/phlex/csv.rb:138
  def delimiter; end

  # pkg:gem/phlex#lib/phlex/csv.rb:146
  def each_item(&_arg0); end

  # pkg:gem/phlex#lib/phlex/csv.rb:130
  def filename; end

  private

  # pkg:gem/phlex#lib/phlex/csv.rb:165
  def __escape__(buffer, value, escape_csv_injection:, strip_whitespace:, escape_regex:); end

  # pkg:gem/phlex#lib/phlex/csv.rb:142
  def column(header = T.unsafe(nil), value); end

  # pkg:gem/phlex#lib/phlex/csv.rb:234
  def ensure_escape_csv_injection_configured!; end

  # Override and set to `false` to disable CSV injection escapes or `true` to enable.
  #
  # pkg:gem/phlex#lib/phlex/csv.rb:161
  def escape_csv_injection?; end

  # Handle legacy `view_template` method
  #
  # pkg:gem/phlex#lib/phlex/csv.rb:224
  def method_missing(method_name, *_arg1, **_arg2, &_arg3); end

  # Override and set to `false` to disable rendering headers.
  #
  # pkg:gem/phlex#lib/phlex/csv.rb:151
  def render_headers?; end

  # Handle legacy `view_template` method
  #
  # pkg:gem/phlex#lib/phlex/csv.rb:219
  def respond_to_missing?(method_name, include_private); end

  # Override and set to `true` to strip leading and trailing whitespace from values.
  #
  # pkg:gem/phlex#lib/phlex/csv.rb:156
  def trim_whitespace?; end
end

# pkg:gem/phlex#lib/phlex/csv.rb:4
Phlex::CSV::FORMULA_PREFIXES_MAP = T.let(T.unsafe(nil), Array)

# pkg:gem/phlex#lib/phlex/csv.rb:10
Phlex::CSV::UNDEFINED = T.let(T.unsafe(nil), Object)

# pkg:gem/phlex#lib/phlex/compiler.rb:6
module Phlex::Compiler
  class << self
    # pkg:gem/phlex#lib/phlex/compiler.rb:15
    def compile(component); end

    # pkg:gem/phlex#lib/phlex/compiler.rb:20
    def compile_file(path); end
  end
end

# pkg:gem/phlex#lib/phlex/compiler/class_compiler.rb:3
class Phlex::Compiler::ClassCompiler < ::Refract::Visitor
  # pkg:gem/phlex#lib/phlex/compiler/class_compiler.rb:4
  def initialize(component, path); end

  # pkg:gem/phlex#lib/phlex/compiler/class_compiler.rb:11
  def compile(node); end

  # pkg:gem/phlex#lib/phlex/compiler/class_compiler.rb:44
  def visit_block_node(node); end

  # pkg:gem/phlex#lib/phlex/compiler/class_compiler.rb:36
  def visit_class_node(node); end

  # pkg:gem/phlex#lib/phlex/compiler/class_compiler.rb:16
  def visit_def_node(node); end

  # pkg:gem/phlex#lib/phlex/compiler/class_compiler.rb:40
  def visit_module_node(node); end
end

# pkg:gem/phlex#lib/phlex/compiler/compactor.rb:3
class Phlex::Compiler::Compactor < ::Refract::MutationVisitor
  # pkg:gem/phlex#lib/phlex/compiler/compactor.rb:4
  def visit_statements_node(node); end
end

# pkg:gem/phlex#lib/phlex/compiler.rb:10
class Phlex::Compiler::Concat < ::Data
  # pkg:gem/phlex#lib/phlex/compiler.rb:12
  def accept(visitor); end

  # pkg:gem/phlex#lib/phlex/compiler.rb:10
  def node; end

  # pkg:gem/phlex#lib/phlex/compiler.rb:11
  def start_line; end

  class << self
    # pkg:gem/phlex#lib/phlex/compiler.rb:10
    def [](*_arg0); end

    # pkg:gem/phlex#lib/phlex/compiler.rb:10
    def inspect; end

    # pkg:gem/phlex#lib/phlex/compiler.rb:10
    def members; end

    # pkg:gem/phlex#lib/phlex/compiler.rb:10
    def new(*_arg0); end
  end
end

# pkg:gem/phlex#lib/phlex/compiler.rb:8
class Phlex::Compiler::Error < ::StandardError; end

# pkg:gem/phlex#lib/phlex/compiler/file_compiler.rb:3
class Phlex::Compiler::FileCompiler < ::Refract::Visitor
  # pkg:gem/phlex#lib/phlex/compiler/file_compiler.rb:6
  def initialize(path); end

  # pkg:gem/phlex#lib/phlex/compiler/file_compiler.rb:13
  def compile(node); end

  # pkg:gem/phlex#lib/phlex/compiler/file_compiler.rb:49
  def visit_block_node(node); end

  # pkg:gem/phlex#lib/phlex/compiler/file_compiler.rb:24
  def visit_class_node(node); end

  # pkg:gem/phlex#lib/phlex/compiler/file_compiler.rb:45
  def visit_def_node(node); end

  # pkg:gem/phlex#lib/phlex/compiler/file_compiler.rb:18
  def visit_module_node(node); end
end

# pkg:gem/phlex#lib/phlex/compiler/file_compiler.rb:4
class Phlex::Compiler::FileCompiler::Result < ::Data
  # pkg:gem/phlex#lib/phlex/compiler/file_compiler.rb:4
  def compiled_snippets; end

  # pkg:gem/phlex#lib/phlex/compiler/file_compiler.rb:4
  def namespace; end

  class << self
    # pkg:gem/phlex#lib/phlex/compiler/file_compiler.rb:4
    def [](*_arg0); end

    # pkg:gem/phlex#lib/phlex/compiler/file_compiler.rb:4
    def inspect; end

    # pkg:gem/phlex#lib/phlex/compiler/file_compiler.rb:4
    def members; end

    # pkg:gem/phlex#lib/phlex/compiler/file_compiler.rb:4
    def new(*_arg0); end
  end
end

# pkg:gem/phlex#lib/phlex/compiler.rb:7
Phlex::Compiler::MAP = T.let(T.unsafe(nil), Hash)

# pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:6
class Phlex::Compiler::MethodCompiler < ::Refract::MutationVisitor
  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:7
  def initialize(component); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:14
  def compile(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:218
  def compile_block_body_node(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:339
  def compile_comment_helper(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:282
  def compile_doctype_helper(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:298
  def compile_fragment_helper(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:306
  def compile_fragment_helper_block(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:247
  def compile_interpolated_string_node(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:161
  def compile_phlex_attributes(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:192
  def compile_phlex_block(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:288
  def compile_plain_helper(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:351
  def compile_raw_helper(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:123
  def compile_standard_element(node, tag); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:145
  def compile_void_element(node, tag); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:266
  def compile_whitespace_helper(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:111
  def visit_block_node(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:87
  def visit_call_node(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:26
  def visit_class_node(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:34
  def visit_def_node(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:30
  def visit_module_node(node); end

  private

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:401
  def buffer(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:530
  def buffer_local; end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:502
  def comment_helper?(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:490
  def doctype_helper?(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:498
  def fragment_helper?(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:371
  def interpolate(statements); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:417
  def output_block?(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:511
  def own_method_without_scope?(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:356
  def plain(value); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:494
  def plain_helper?(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:361
  def raw(value); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:506
  def raw_helper?(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:548
  def self_local; end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:561
  def should_render_local; end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:434
  def standard_element?(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:515
  def state_local; end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:454
  def static_attribute_value_literal?(value); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:429
  def static_content_block?(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:475
  def static_token_value_literal?(value); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:444
  def void_element?(node); end

  # pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:486
  def whitespace_helper?(node); end
end

# pkg:gem/phlex#lib/phlex/compiler/method_compiler.rb:510
Phlex::Compiler::MethodCompiler::ALLOWED_OWNERS = T.let(T.unsafe(nil), Set)

# pkg:gem/phlex#lib/phlex.rb:26
Phlex::DEPLOYED_AT = T.let(T.unsafe(nil), Integer)

# pkg:gem/phlex#lib/phlex/errors/double_render_error.rb:3
class Phlex::DoubleRenderError < ::RuntimeError
  include ::Phlex::Error
end

# @api private
#
# pkg:gem/phlex#lib/phlex/error.rb:4
module Phlex::Error; end

# pkg:gem/phlex#lib/phlex.rb:24
Phlex::Escape = ERB::Escape

# @api private
#
# pkg:gem/phlex#lib/phlex/fifo.rb:4
class Phlex::FIFO
  # pkg:gem/phlex#lib/phlex/fifo.rb:5
  def initialize(max_bytesize: T.unsafe(nil), max_value_bytesize: T.unsafe(nil)); end

  # pkg:gem/phlex#lib/phlex/fifo.rb:21
  def [](key); end

  # pkg:gem/phlex#lib/phlex/fifo.rb:26
  def []=(key, value); end

  # pkg:gem/phlex#lib/phlex/fifo.rb:13
  def bytesize; end

  # pkg:gem/phlex#lib/phlex/fifo.rb:49
  def clear; end

  # pkg:gem/phlex#lib/phlex/fifo.rb:15
  def expand(bytes); end

  # pkg:gem/phlex#lib/phlex/fifo.rb:13
  def max_bytesize; end

  # pkg:gem/phlex#lib/phlex/fifo.rb:45
  def size; end
end

# An extremely fast in-memory cache store that evicts keys on a first-in-first-out basis.
#
# pkg:gem/phlex#lib/phlex/fifo_cache_store.rb:4
class Phlex::FIFOCacheStore
  # pkg:gem/phlex#lib/phlex/fifo_cache_store.rb:5
  def initialize(max_bytesize: T.unsafe(nil)); end

  # pkg:gem/phlex#lib/phlex/fifo_cache_store.rb:27
  def clear; end

  # pkg:gem/phlex#lib/phlex/fifo_cache_store.rb:12
  def fetch(key); end

  private

  # pkg:gem/phlex#lib/phlex/fifo_cache_store.rb:31
  def map_key(value); end
end

# pkg:gem/phlex#lib/phlex/html.rb:3
class Phlex::HTML < ::Phlex::SGML
  include ::Phlex::HTML::StandardElements
  include ::Phlex::HTML::VoidElements
  extend ::Phlex::SGML::Elements

  # Returns the string "text/html"
  #
  # pkg:gem/phlex#lib/phlex/html.rb:34
  def content_type; end

  # Output an HTML doctype.
  #
  # pkg:gem/phlex#lib/phlex/html.rb:8
  def doctype; end

  # Override to provide a filename for the HTML file
  #
  # pkg:gem/phlex#lib/phlex/html.rb:29
  def filename; end

  # Outputs an `<svg>` tag.
  #
  # [MDN Docs](https://developer.mozilla.org/docs/Web/SVG/Element/svg)
  # [Spec](https://html.spec.whatwg.org/#the-svg-element)
  #
  # pkg:gem/phlex#lib/phlex/html.rb:20
  def svg(*_arg0, **_arg1, &_arg2); end

  # Output an HTML tag dynamically, e.g:
  #
  # ```ruby
  # @tag_name = :h1
  # tag(@tag_name, class: "title")
  # ```
  #
  # pkg:gem/phlex#lib/phlex/html.rb:44
  def tag(name, **attributes, &_arg2); end
end

# Standard HTML elements accept content and always have a closing tag.
#
# pkg:gem/phlex#lib/phlex/html/standard_elements.rb:4
module Phlex::HTML::StandardElements
  extend ::Phlex::SGML::Elements

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:11
  def a(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:17
  def abbr(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:23
  def address(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:29
  def article(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:35
  def aside(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:42
  def audio(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:48
  def b(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:54
  def bdi(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:60
  def bdo(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:66
  def blockquote(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:72
  def body(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:79
  def button(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:85
  def canvas(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:91
  def caption(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:97
  def cite(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:103
  def code(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:109
  def colgroup(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:115
  def data(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:121
  def datalist(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:127
  def dd(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:133
  def del(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:140
  def details(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:146
  def dfn(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:153
  def dialog(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:159
  def div(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:165
  def dl(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:171
  def dt(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:177
  def em(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:183
  def fencedframe(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:189
  def fieldset(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:195
  def figcaption(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:201
  def figure(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:207
  def footer(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:213
  def form(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:219
  def h1(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:225
  def h2(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:231
  def h3(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:237
  def h4(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:243
  def h5(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:249
  def h6(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:255
  def head(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:261
  def header(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:267
  def hgroup(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:273
  def html(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:279
  def i(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:285
  def iframe(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:291
  def ins(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:297
  def kbd(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:303
  def label(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:309
  def legend(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:315
  def li(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:321
  def main(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:327
  def map(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:333
  def mark(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:339
  def menu(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:345
  def meter(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:351
  def nav(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:357
  def noscript(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:363
  def object(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:369
  def ol(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:375
  def optgroup(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:381
  def option(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:387
  def output(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:393
  def p(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:400
  def picture(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:406
  def pre(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:412
  def progress(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:418
  def q(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:424
  def rp(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:430
  def rt(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:436
  def ruby(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:442
  def s(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:448
  def samp(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:454
  def script(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:461
  def search(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:467
  def section(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:473
  def select(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:480
  def selectedcontent(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:486
  def slot(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:492
  def small(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:498
  def span(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:504
  def strong(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:510
  def style(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:516
  def sub(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:523
  def summary(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:529
  def sup(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:535
  def svg(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:541
  def table(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:547
  def tbody(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:553
  def td(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:559
  def template(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:565
  def textarea(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:571
  def tfoot(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:577
  def th(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:583
  def thead(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:589
  def time(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:595
  def title(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:601
  def tr(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:607
  def u(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:613
  def ul(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:619
  def var(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:626
  def video(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/standard_elements.rb:632
  def wbr(**attributes); end
end

# Void HTML elements don't accept content and never have a closing tag.
#
# pkg:gem/phlex#lib/phlex/html/void_elements.rb:4
module Phlex::HTML::VoidElements
  extend ::Phlex::SGML::Elements

  # pkg:gem/phlex#lib/phlex/html/void_elements.rb:10
  def area(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/void_elements.rb:15
  def base(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/void_elements.rb:20
  def br(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/void_elements.rb:25
  def col(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/void_elements.rb:30
  def embed(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/void_elements.rb:35
  def hr(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/void_elements.rb:40
  def img(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/void_elements.rb:45
  def input(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/void_elements.rb:50
  def link(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/void_elements.rb:55
  def meta(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/void_elements.rb:60
  def source(**attributes); end

  # pkg:gem/phlex#lib/phlex/html/void_elements.rb:65
  def track(**attributes); end
end

# @api private
#
# pkg:gem/phlex#lib/phlex/helpers.rb:4
module Phlex::Helpers
  private

  # pkg:gem/phlex#lib/phlex/helpers.rb:44
  def grab(**bindings); end

  # pkg:gem/phlex#lib/phlex/helpers.rb:5
  def mix(*args); end
end

# pkg:gem/phlex#lib/phlex/kit.rb:3
module Phlex::Kit
  # pkg:gem/phlex#lib/phlex/kit.rb:47
  def const_added(name); end

  # pkg:gem/phlex#lib/phlex/kit.rb:35
  def method_missing(name, *_arg1, **_arg2, &_arg3); end

  private

  # pkg:gem/phlex#lib/phlex/kit.rb:43
  def respond_to_missing?(name, include_private = T.unsafe(nil)); end

  class << self
    # pkg:gem/phlex#lib/phlex/kit.rb:22
    def extended(mod); end
  end
end

# pkg:gem/phlex#lib/phlex/kit.rb:4
module Phlex::Kit::LazyLoader
  # pkg:gem/phlex#lib/phlex/kit.rb:5
  def method_missing(name, *_arg1, **_arg2, &_arg3); end

  private

  # pkg:gem/phlex#lib/phlex/kit.rb:15
  def respond_to_missing?(name, include_private = T.unsafe(nil)); end
end

# pkg:gem/phlex#lib/phlex.rb:8
Phlex::Loader = T.let(T.unsafe(nil), Zeitwerk::GemLoader)

# pkg:gem/phlex#lib/phlex/errors/name_error.rb:3
class Phlex::NameError < ::NameError
  include ::Phlex::Error
end

# pkg:gem/phlex#lib/phlex/errors/runtime_error.rb:3
class Phlex::RuntimeError < ::RuntimeError
  include ::Phlex::Error
end

# **Standard Generalized Markup Language** for behaviour common to {HTML} and {SVG}.
#
# pkg:gem/phlex#lib/phlex/sgml.rb:4
class Phlex::SGML
  include ::Phlex::Helpers

  # pkg:gem/phlex#lib/phlex/sgml.rb:433
  def __map_exception__(exception); end

  # Cache a block of content.
  #
  # ```ruby
  # @products.each do |product|
  #   cache product do
  #     h1 { product.name }
  #   end
  # end
  # ```
  #
  # pkg:gem/phlex#lib/phlex/sgml.rb:236
  def cache(*cache_key, **_arg1, &content); end

  # pkg:gem/phlex#lib/phlex/sgml.rb:38
  def call(buffer = T.unsafe(nil), context: T.unsafe(nil), fragments: T.unsafe(nil), &_arg3); end

  # Capture the output of the block and returns it as a string.
  #
  # pkg:gem/phlex#lib/phlex/sgml.rb:164
  def capture(*args, &block); end

  # Wrap the output in an HTML comment.
  #
  # [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Comments)
  #
  # pkg:gem/phlex#lib/phlex/sgml.rb:134
  def comment(&_arg0); end

  # pkg:gem/phlex#lib/phlex/sgml.rb:89
  def context; end

  # Flush the current state to the output buffer.
  #
  # pkg:gem/phlex#lib/phlex/sgml.rb:196
  def flush; end

  # Define a named fragment that can be selectively rendered.
  #
  # pkg:gem/phlex#lib/phlex/sgml.rb:175
  def fragment(name); end

  # pkg:gem/phlex#lib/phlex/sgml.rb:50
  def internal_call(parent: T.unsafe(nil), state: T.unsafe(nil), &block); end

  # pkg:gem/phlex#lib/phlex/sgml.rb:288
  def json_escape(string); end

  # Cache a block of content where you control the entire cache key.
  # If you really know what you’re doing and want to take full control
  # and responsibility for the cache key, use this method.
  #
  # ```ruby
  # low_level_cache([Commonmarker::VERSION, Digest::MD5.hexdigest(@content)]) do
  #   markdown(@content)
  # end
  # ```
  #
  # Note: To allow you more control, this method does not take a splat of cache keys.
  # If you need to pass multiple cache keys, you should pass an array.
  #
  # pkg:gem/phlex#lib/phlex/sgml.rb:265
  def low_level_cache(cache_key, **options, &content); end

  # Output plain text.
  #
  # pkg:gem/phlex#lib/phlex/sgml.rb:106
  def plain(content); end

  # Output the given safe object as-is. You may need to use `safe` to mark a string as a safe object.
  #
  # pkg:gem/phlex#lib/phlex/sgml.rb:148
  def raw(content); end

  # pkg:gem/phlex#lib/phlex/sgml.rb:200
  def render(renderable = T.unsafe(nil), &_arg1); end

  # Returns `false` before rendering and `true` once the component has started rendering.
  # It will not reset back to false after rendering.
  #
  # pkg:gem/phlex#lib/phlex/sgml.rb:101
  def rendering?; end

  # Mark the given string as safe for HTML output.
  #
  # pkg:gem/phlex#lib/phlex/sgml.rb:184
  def safe(value); end

  # pkg:gem/phlex#lib/phlex/sgml.rb:34
  def to_proc; end

  # pkg:gem/phlex#lib/phlex/sgml.rb:26
  def view_template; end

  # Output a single space character. If a block is given, a space will be output before and after the block.
  #
  # pkg:gem/phlex#lib/phlex/sgml.rb:115
  def whitespace(&_arg0); end

  # pkg:gem/phlex#lib/phlex/sgml.rb:193
  def 🦺(value); end

  private

  # pkg:gem/phlex#lib/phlex/sgml.rb:371
  def __implicit_output__(content); end

  # pkg:gem/phlex#lib/phlex/sgml.rb:418
  def __render_attributes__(attributes); end

  # same as __implicit_output__ but escapes even `safe` objects
  #
  # pkg:gem/phlex#lib/phlex/sgml.rb:396
  def __text__(content); end

  # pkg:gem/phlex#lib/phlex/sgml.rb:335
  def __yield_content__; end

  # pkg:gem/phlex#lib/phlex/sgml.rb:359
  def __yield_content_with_args__(*a); end

  # pkg:gem/phlex#lib/phlex/sgml.rb:347
  def __yield_content_with_no_yield_args__; end

  # pkg:gem/phlex#lib/phlex/sgml.rb:331
  def after_template; end

  # Override this method to use a different deployment key.
  #
  # pkg:gem/phlex#lib/phlex/sgml.rb:293
  def app_version_key; end

  # pkg:gem/phlex#lib/phlex/sgml.rb:322
  def around_template; end

  # pkg:gem/phlex#lib/phlex/sgml.rb:327
  def before_template; end

  # Override this method to use a different cache store.
  #
  # pkg:gem/phlex#lib/phlex/sgml.rb:298
  def cache_store; end

  # pkg:gem/phlex#lib/phlex/sgml.rb:302
  def enable_cache_reloading?; end

  # pkg:gem/phlex#lib/phlex/sgml.rb:315
  def format_object(object); end

  # pkg:gem/phlex#lib/phlex/sgml.rb:311
  def render?; end

  # pkg:gem/phlex#lib/phlex/sgml.rb:306
  def vanish(*_arg0, **_arg1, &_arg2); end

  class << self
    # pkg:gem/phlex#lib/phlex/sgml.rb:436
    def __compile__(method_name); end

    # Render the view to a String. Arguments are delegated to {.new}.
    #
    # pkg:gem/phlex#lib/phlex/sgml.rb:9
    def call(*_arg0, **_arg1, &_arg2); end

    # Create a new instance of the component.
    # @note The block will not be delegated to {#initialize}. Instead, it will be sent to {#view_template} when rendering.
    #
    # pkg:gem/phlex#lib/phlex/sgml.rb:15
    def new(*a, **k, &block); end

    private

    # pkg:gem/phlex#lib/phlex/sgml.rb:424
    def method_added(method_name); end
  end
end

# pkg:gem/phlex#lib/phlex/sgml/attributes.rb:3
module Phlex::SGML::Attributes
  extend ::Phlex::SGML::Attributes

  # pkg:gem/phlex#lib/phlex/sgml/attributes.rb:171
  def decode_html_character_references(value); end

  # pkg:gem/phlex#lib/phlex/sgml/attributes.rb:15
  def generate_attributes(attributes, buffer = T.unsafe(nil)); end

  # Provides the nested-attributes case for serializing out attributes.
  # This allows us to skip many of the checks the `__attributes__` method must perform.
  #
  # pkg:gem/phlex#lib/phlex/sgml/attributes.rb:118
  def generate_nested_attributes(attributes, base_name, buffer = T.unsafe(nil)); end

  # pkg:gem/phlex#lib/phlex/sgml/attributes.rb:192
  def generate_nested_tokens(tokens, sep = T.unsafe(nil), gsub_from = T.unsafe(nil), gsub_to = T.unsafe(nil)); end

  # The result is unsafe so should be escaped.
  #
  # pkg:gem/phlex#lib/phlex/sgml/attributes.rb:251
  def generate_styles(styles); end
end

# pkg:gem/phlex#lib/phlex/sgml/attributes.rb:8
Phlex::SGML::Attributes::NAMED_CHARACTER_REFERENCES = T.let(T.unsafe(nil), Hash)

# pkg:gem/phlex#lib/phlex/sgml/attributes.rb:7
Phlex::SGML::Attributes::REF_ATTRIBUTES = T.let(T.unsafe(nil), Set)

# pkg:gem/phlex#lib/phlex/sgml/attributes.rb:6
Phlex::SGML::Attributes::UNSAFE_ATTRIBUTES = T.let(T.unsafe(nil), Set)

# pkg:gem/phlex#lib/phlex/sgml/attributes.rb:13
Phlex::SGML::Attributes::UNSAFE_ATTRIBUTE_NAME_CHARS = T.let(T.unsafe(nil), Regexp)

# pkg:gem/phlex#lib/phlex/sgml/elements.rb:3
module Phlex::SGML::Elements
  # pkg:gem/phlex#lib/phlex/sgml/elements.rb:140
  def __register_void_element__(method_name, tag: T.unsafe(nil)); end

  # pkg:gem/phlex#lib/phlex/sgml/elements.rb:39
  def __registered_elements__; end

  # pkg:gem/phlex#lib/phlex/sgml/elements.rb:43
  def register_element(method_name, tag: T.unsafe(nil)); end
end

# pkg:gem/phlex#lib/phlex/sgml/elements.rb:4
Phlex::SGML::Elements::COMMA_SEPARATED_TOKENS = T.let(T.unsafe(nil), Hash)

# @api private
#
# pkg:gem/phlex#lib/phlex/sgml/safe_object.rb:4
module Phlex::SGML::SafeObject; end

# pkg:gem/phlex#lib/phlex/sgml/safe_value.rb:3
class Phlex::SGML::SafeValue
  include ::Phlex::SGML::SafeObject

  # pkg:gem/phlex#lib/phlex/sgml/safe_value.rb:6
  def initialize(to_s); end

  # pkg:gem/phlex#lib/phlex/sgml/safe_value.rb:10
  def to_s; end
end

# pkg:gem/phlex#lib/phlex/sgml/state.rb:3
class Phlex::SGML::State
  # pkg:gem/phlex#lib/phlex/sgml/state.rb:4
  def initialize(output_buffer:, fragments:, user_context: T.unsafe(nil)); end

  # pkg:gem/phlex#lib/phlex/sgml/state.rb:19
  def around_render(component); end

  # pkg:gem/phlex#lib/phlex/sgml/state.rb:36
  def begin_fragment(id); end

  # pkg:gem/phlex#lib/phlex/sgml/state.rb:17
  def buffer; end

  # pkg:gem/phlex#lib/phlex/sgml/state.rb:78
  def caching(&_arg0); end

  # pkg:gem/phlex#lib/phlex/sgml/state.rb:90
  def caching?; end

  # pkg:gem/phlex#lib/phlex/sgml/state.rb:94
  def capture; end

  # pkg:gem/phlex#lib/phlex/sgml/state.rb:15
  def capturing; end

  # pkg:gem/phlex#lib/phlex/sgml/state.rb:15
  def capturing=(_arg0); end

  # pkg:gem/phlex#lib/phlex/sgml/state.rb:53
  def end_fragment(id); end

  # pkg:gem/phlex#lib/phlex/sgml/state.rb:114
  def flush; end

  # pkg:gem/phlex#lib/phlex/sgml/state.rb:17
  def fragment_depth; end

  # pkg:gem/phlex#lib/phlex/sgml/state.rb:17
  def fragments; end

  # pkg:gem/phlex#lib/phlex/sgml/state.rb:17
  def output_buffer; end

  # pkg:gem/phlex#lib/phlex/sgml/state.rb:69
  def record_fragment(id, offset, length, nested_fragments); end

  # pkg:gem/phlex#lib/phlex/sgml/state.rb:32
  def should_render?; end

  # pkg:gem/phlex#lib/phlex/sgml/state.rb:15
  def user_context; end

  # pkg:gem/phlex#lib/phlex/sgml/state.rb:15
  def user_context=(_arg0); end
end

# pkg:gem/phlex#lib/phlex/svg.rb:3
class Phlex::SVG < ::Phlex::SGML
  include ::Phlex::SVG::StandardElements

  # pkg:gem/phlex#lib/phlex/svg.rb:16
  def cdata(content = T.unsafe(nil), &block); end

  # Returns the string "image/svg+xml"
  #
  # pkg:gem/phlex#lib/phlex/svg.rb:7
  def content_type; end

  # Override to provide a filename for the SVG file
  #
  # pkg:gem/phlex#lib/phlex/svg.rb:12
  def filename; end

  # pkg:gem/phlex#lib/phlex/svg.rb:30
  def tag(name, **attributes, &_arg2); end
end

# pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:3
module Phlex::SVG::StandardElements
  extend ::Phlex::SGML::Elements

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:8
  def a(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:22
  def animate(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:32
  def animateMotion(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:57
  def animateTransform(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:63
  def circle(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:69
  def clipPath(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:75
  def defs(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:81
  def desc(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:87
  def discard(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:93
  def ellipse(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:99
  def feBlend(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:105
  def feColorMatrix(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:111
  def feComponentTransfer(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:117
  def feComposite(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:123
  def feConvolveMatrix(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:129
  def feDiffuseLighting(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:135
  def feDisplacementMap(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:141
  def feDistantLight(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:147
  def feDropShadow(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:153
  def feFlood(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:159
  def feFuncA(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:165
  def feFuncB(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:171
  def feFuncG(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:177
  def feFuncR(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:183
  def feGaussianBlur(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:189
  def feImage(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:195
  def feMerge(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:201
  def feMergeNode(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:207
  def feMorphology(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:213
  def feOffset(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:219
  def fePointLight(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:225
  def feSpecularLighting(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:231
  def feSpotLight(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:237
  def feTile(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:243
  def feTurbulence(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:249
  def filter(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:255
  def foreignObject(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:261
  def g(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:267
  def image(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:273
  def line(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:279
  def linearGradient(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:285
  def marker(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:291
  def mask(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:297
  def metadata(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:303
  def mpath(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:309
  def path(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:315
  def pattern(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:321
  def polygon(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:327
  def polyline(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:333
  def radialGradient(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:339
  def rect(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:345
  def script(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:351
  def set(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:357
  def stop(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:363
  def style(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:369
  def svg(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:375
  def switch(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:381
  def symbol(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:387
  def text(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:393
  def textPath(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:399
  def title(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:405
  def tspan(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:411
  def use(**attributes); end

  # pkg:gem/phlex#lib/phlex/svg/standard_elements.rb:417
  def view(**attributes); end
end

# pkg:gem/phlex#lib/phlex.rb:30
Phlex::UNBOUND_INSTANCE_METHOD_METHOD = T.let(T.unsafe(nil), UnboundMethod)

# pkg:gem/phlex#lib/phlex/version.rb:4
Phlex::VERSION = T.let(T.unsafe(nil), String)
