# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby_llm-skills` gem.
# Please instead update this file by running `bin/tapioca gem ruby_llm-skills`.


# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/version.rb:3
module RubyLLM; end

class RubyLLM::Agent
  include ::RubyLLM::Skills::AgentExtensions
  include ::RubyLLM::Skills::AgentExtensions::InstanceMethods
  extend ::RubyLLM::Skills::AgentExtensions::ClassMethods
  extend ::RubyLLM::Skills::AgentExtensions::ConfigurationPatch
end

class RubyLLM::Chat
  include ::RubyLLM::Skills::ChatExtensions
end

# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/version.rb:4
module RubyLLM::Skills
  class << self
    # Create a composite loader from multiple sources.
    #
    # @param loaders [Array<Loader>] loaders to combine
    # @return [CompositeLoader] combined loader
    # @example
    #   RubyLLM::Skills.compose(
    #     RubyLLM::Skills.from_directory("app/skills"),
    #     RubyLLM::Skills.from_database(Skill.all)
    #   )
    #
    # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills.rb:117
    def compose(*loaders); end

    # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills.rb:70
    def default_path; end

    # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills.rb:70
    def default_path=(_arg0); end

    # Load skills from database records.
    #
    # @param records [ActiveRecord::Relation, Array] collection of skill records
    # @return [DatabaseLoader] loader for the records
    # @example
    #   RubyLLM::Skills.from_database(Skill.where(active: true))
    #
    # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills.rb:103
    def from_database(records); end

    # Load skills from a filesystem directory.
    #
    # @param path [String] path to skills directory (defaults to default_path)
    # @return [FilesystemLoader] loader for the directory
    # @example
    #   RubyLLM::Skills.from_directory("app/skills")
    #
    # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills.rb:78
    def from_directory(path = T.unsafe(nil)); end

    # Load a single skill from a directory.
    #
    # @param path [String] path to skill directory (containing SKILL.md)
    # @return [Skill] the loaded skill
    # @raise [LoadError] if SKILL.md not found
    # @example
    #   RubyLLM::Skills.load("app/skills/my-skill")
    #
    # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills.rb:89
    def load(path); end
  end
end

# Extensions for ActiveRecord models using acts_as_chat.
#
# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/chat_extensions.rb:95
module RubyLLM::Skills::ActiveRecordExtensions
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/chat_extensions.rb:96
  def with_skills(*sources, only: T.unsafe(nil)); end
end

# Extensions for RubyLLM::Agent to enable declarative skill configuration.
#
# @example Static skills
#   class SupportAgent < RubyLLM::Agent
#     skills "app/skills", only: [:faq]
#   end
#
# @example Dynamic skills
#   class WorkspaceAgent < RubyLLM::Agent
#     inputs :workspace
#     skills { [workspace.skill_collection] }
#   end
#
# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/agent_extensions.rb:18
module RubyLLM::Skills::AgentExtensions
  class << self
    # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/agent_extensions.rb:132
    def included(base); end
  end
end

# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/agent_extensions.rb:21
module RubyLLM::Skills::AgentExtensions::ClassMethods
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/agent_extensions.rb:27
  def inherited(subclass); end

  # Declare skill sources for this agent class.
  #
  # Called with no arguments, returns the current configuration.
  # Called with sources or a block, sets the configuration.
  #
  # @param sources [Array] skill sources
  # @param only [Array<Symbol, String>, nil] include only these skills
  # @return [Hash] current configuration when called as a getter
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/agent_extensions.rb:41
  def skills(*sources, only: T.unsafe(nil), &block); end

  private

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/agent_extensions.rb:73
  def database_collection_source?(source); end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/agent_extensions.rb:59
  def flatten_skill_sources(source); end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/agent_extensions.rb:69
  def loader_source?(source); end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/agent_extensions.rb:55
  def normalize_skill_sources(raw_sources); end

  class << self
    # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/agent_extensions.rb:22
    def extended(base); end
  end
end

# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/agent_extensions.rb:90
module RubyLLM::Skills::AgentExtensions::ConfigurationPatch
  private

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/agent_extensions.rb:93
  def apply_configuration(chat_object, **kwargs); end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/agent_extensions.rb:100
  def apply_skills(llm_chat, runtime); end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/agent_extensions.rb:127
  def valid_skill_source?(source); end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/agent_extensions.rb:118
  def validate_skill_sources!(sources); end
end

# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/agent_extensions.rb:78
module RubyLLM::Skills::AgentExtensions::InstanceMethods
  # Add skills to this agent instance at runtime.
  #
  # @param sources [Array] skill sources
  # @param only [Array<Symbol, String>, nil] include only these skills
  # @return [self] for chaining
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/agent_extensions.rb:84
  def with_skills(*sources, only: T.unsafe(nil)); end
end

# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/agent_extensions.rb:19
RubyLLM::Skills::AgentExtensions::REQUIRED_AGENT_SINGLETON_METHODS = T.let(T.unsafe(nil), Array)

# Extensions for RubyLLM::Chat to enable skill integration.
#
# @example Default (app/skills)
#   chat.with_skills
#
# @example Custom path
#   chat.with_skills("lib/skills")
#
# @example Multiple sources (auto-detected)
#   chat.with_skills("app/skills", "app/commands", user.skills)
#
# @example Filter skills
#   chat.with_skills(only: [:pdf_report])
#
# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/chat_extensions.rb:21
module RubyLLM::Skills::ChatExtensions
  # Add skills to this chat.
  #
  # @param sources [Array] skill sources - auto-detects type (directory, zip, collection)
  # @param only [Array<Symbol, String>, nil] include only these skills
  # @return [self] for chaining
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/chat_extensions.rb:27
  def with_skills(*sources, only: T.unsafe(nil)); end

  private

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/chat_extensions.rb:58
  def database_collection_source?(source); end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/chat_extensions.rb:54
  def loader_source?(source); end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/chat_extensions.rb:40
  def to_loader(source); end
end

# Base error class for all skills-related errors.
# Rescue this to catch any error from the gem.
#
# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/error.rb:7
class RubyLLM::Skills::Error < ::StandardError; end

# Loads skills from a filesystem directory.
#
# Supports two formats:
# 1. Directory skills: subdirectories containing SKILL.md files
# 2. Single-file commands: .md files with frontmatter at the root level
#
# @example Directory skills
#   app/skills/
#   └── pdf-report/
#       └── SKILL.md
#
# @example Single-file commands
#   app/commands/
#   └── write-poem.md
#
# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/filesystem_loader.rb:20
class RubyLLM::Skills::FilesystemLoader < ::RubyLLM::Skills::Loader
  # Initialize with a directory path.
  #
  # @param path [String, Pathname] path to skills directory
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/filesystem_loader.rb:26
  def initialize(path); end

  # List all skills from the directory.
  #
  # @return [Array<Skill>] skills found in directory
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/filesystem_loader.rb:34
  def list; end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/filesystem_loader.rb:21
  def path; end

  protected

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/filesystem_loader.rb:40
  def load_all; end

  private

  # Load skills from subdirectories containing SKILL.md
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/filesystem_loader.rb:49
  def directory_skills; end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/filesystem_loader.rb:68
  def load_directory_skill(skill_md_path); end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/filesystem_loader.rb:75
  def load_single_file_skill(md_path); end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/filesystem_loader.rb:83
  def log_warning(message); end

  # Load single-file .md commands from root level
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/filesystem_loader.rb:59
  def single_file_skills; end
end

# Simple wrapper that filters skills by name.
#
# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/chat_extensions.rb:64
class RubyLLM::Skills::FilteredLoader
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/chat_extensions.rb:65
  def initialize(loader, only); end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/chat_extensions.rb:84
  def exists?(name); end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/chat_extensions.rb:74
  def find(name); end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/chat_extensions.rb:79
  def get(name); end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/chat_extensions.rb:70
  def list; end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/chat_extensions.rb:88
  def reload!; end
end

# Raised when a skill has invalid structure or content.
#
# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/error.rb:10
class RubyLLM::Skills::InvalidSkillError < ::RubyLLM::Skills::Error; end

# Raised when skill loading fails (filesystem, zip, database).
#
# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/error.rb:16
class RubyLLM::Skills::LoadError < ::RubyLLM::Skills::Error; end

# Base class for skill loaders.
#
# Loaders are responsible for discovering and loading skills from various sources:
# - FilesystemLoader: loads from directory structures
# - ZipLoader: loads from .zip archives
# - DatabaseLoader: loads from ActiveRecord models
#
# @example
#   loader = FilesystemLoader.new("app/skills")
#   loader.list         # => [skill1, skill2, ...]
#   loader.find("name") # => Skill or nil
#   loader.get("name")  # => Skill or raises NotFoundError
#
# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/loader.rb:18
class RubyLLM::Skills::Loader
  # Check if a skill exists.
  #
  # @param name [String] skill name
  # @return [Boolean] true if skill exists
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/loader.rb:50
  def exists?(name); end

  # Find a skill by name.
  #
  # @param name [String] skill name
  # @return [Skill, nil] skill or nil if not found
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/loader.rb:30
  def find(name); end

  # Get a skill by name, raising if not found.
  #
  # @param name [String] skill name
  # @return [Skill] the found skill
  # @raise [NotFoundError] if skill not found
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/loader.rb:39
  def get(name); end

  # List all skills from this source.
  #
  # @return [Array<Skill>] collection of skills
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/loader.rb:22
  def list; end

  # Reload all skills, clearing any cache.
  #
  # @return [self]
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/loader.rb:57
  def reload!; end

  protected

  # Subclasses must implement this to load all skills.
  #
  # @return [Array<Skill>] all skills from source
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/loader.rb:72
  def load_all; end

  # Cache skills from #load_all for performance.
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/loader.rb:65
  def skills; end
end

# Raised when a requested skill cannot be found.
#
# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/error.rb:13
class RubyLLM::Skills::NotFoundError < ::RubyLLM::Skills::Error; end

# Raised when YAML frontmatter parsing fails.
#
# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/error.rb:19
class RubyLLM::Skills::ParseError < ::RubyLLM::Skills::Error; end

# Parses SKILL.md files with YAML frontmatter.
#
# A valid SKILL.md has the format:
#   ---
#   name: skill-name
#   description: What the skill does
#   ---
#   # Skill content here
#
# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/parser.rb:16
class RubyLLM::Skills::Parser
  class << self
    # Extract the body content (everything after frontmatter).
    #
    # @param content [String] full SKILL.md content
    # @return [String] body content without frontmatter
    #
    # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/parser.rb:55
    def extract_body(content); end

    # Parse a SKILL.md file and extract frontmatter metadata.
    #
    # @param path [String, Pathname] path to SKILL.md file
    # @return [Hash] parsed frontmatter as hash
    # @raise [ParseError] if frontmatter is missing or invalid
    #
    # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/parser.rb:26
    def parse_file(path); end

    # Parse SKILL.md content string and extract frontmatter.
    #
    # @param content [String] full SKILL.md content
    # @return [Hash] parsed frontmatter as hash
    # @raise [ParseError] if frontmatter is missing or invalid
    #
    # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/parser.rb:40
    def parse_string(content); end

    private

    # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/parser.rb:64
    def parse_yaml(yaml_content); end
  end
end

# Regex to match YAML frontmatter between --- delimiters
#
# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/parser.rb:18
RubyLLM::Skills::Parser::FRONTMATTER_REGEX = T.let(T.unsafe(nil), Regexp)

# Rails integration for RubyLLM::Skills.
#
# Sets up the default skills path to Rails.root/app/skills
# and configures autoloading of skill files.
#
# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/railtie.rb:10
class RubyLLM::Skills::Railtie < ::Rails::Railtie; end

# Represents a single skill with its metadata and content.
#
# Skills follow a progressive disclosure pattern:
# - Level 1: Metadata (name, description) - loaded immediately
# - Level 2: Content (SKILL.md body) - loaded lazily on demand
# - Level 3: Resources (scripts, references, assets) - loaded lazily
#
# @example
#   skill = Skill.new(
#     path: "app/skills/pdf-report",
#     metadata: { "name" => "pdf-report", "description" => "Generate PDFs" }
#   )
#   skill.name        # => "pdf-report" (immediate)
#   skill.content     # => loads SKILL.md body (lazy)
#   skill.scripts     # => lists script files (lazy)
#
# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:21
class RubyLLM::Skills::Skill
  # Initialize a skill from parsed metadata.
  #
  # @param path [String] path to skill directory, file, or virtual identifier
  # @param metadata [Hash] parsed YAML frontmatter
  # @param content [String, nil] pre-loaded content (optional)
  # @param virtual [Boolean] force virtual mode (no filesystem access)
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:30
  def initialize(path:, metadata:, content: T.unsafe(nil), virtual: T.unsafe(nil)); end

  # @return [Array<String>] list of allowed tools (experimental)
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:63
  def allowed_tools; end

  # List asset files in the assets/ directory.
  # Loaded lazily on first access.
  #
  # @return [Array<String>] paths to asset files
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:95
  def assets; end

  # @return [String, nil] compatibility info from frontmatter
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:53
  def compatibility; end

  # Get the full SKILL.md content (body without frontmatter).
  # Content is loaded lazily on first access.
  #
  # @return [String] skill instructions
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:71
  def content; end

  # @return [Hash] custom metadata key-value pairs
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:58
  def custom_metadata; end

  # @return [String] skill description from frontmatter
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:43
  def description; end

  # Get validation errors.
  #
  # @return [Array<String>] list of error messages
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:132
  def errors; end

  # Check if skill path is a filesystem path (vs database virtual path).
  #
  # @return [Boolean] true if path points to filesystem
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:102
  def filesystem?; end

  # @return [String] inspection string
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:147
  def inspect; end

  # @return [String, nil] license from frontmatter
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:48
  def license; end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:22
  def metadata; end

  # @return [String] skill name from frontmatter
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:38
  def name; end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:22
  def path; end

  # List reference files in the references/ directory.
  # Loaded lazily on first access.
  #
  # @return [Array<String>] paths to reference files
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:87
  def references; end

  # Clear cached content and resources (useful for testing).
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:137
  def reload!; end

  # List script files in the scripts/ directory.
  # Loaded lazily on first access.
  #
  # @return [Array<String>] paths to script files
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:79
  def scripts; end

  # Path to the SKILL.md file.
  #
  # @return [String, nil] path to SKILL.md or nil for virtual skills
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:116
  def skill_md_path; end

  # Validate the skill structure.
  #
  # @return [Boolean] true if skill is valid
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:125
  def valid?; end

  # Check if skill is a virtual/database skill (no filesystem resources).
  #
  # @return [Boolean] true if skill has no filesystem resources
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:109
  def virtual?; end

  private

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:176
  def list_resources(subdir); end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:153
  def load_content; end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill.rb:172
  def single_file?; end
end

# A RubyLLM Tool that enables progressive skill loading.
#
# This tool is the key integration point for LLM skill discovery.
# It embeds skill metadata (name + description) in its description,
# allowing the LLM to discover available skills. When invoked,
# it returns the full skill content.
#
# Progressive Disclosure Pattern:
# 1. Skill metadata is always visible in the tool description (~100 tokens/skill)
# 2. Full skill content is loaded on-demand when the tool is called (~5k tokens)
# 3. Resources (scripts, references) can be loaded separately as needed
#
# @example Basic usage
#   loader = RubyLLM::Skills.from_directory("app/skills")
#   skill_tool = RubyLLM::Skills::SkillTool.new(loader)
#
#   chat.with_tools(skill_tool)
#   chat.ask("Help me generate a PDF report")
#   # LLM sees available skills, calls skill_tool with name="pdf-report"
#   # Tool returns full SKILL.md content for LLM to follow
#
# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill_tool.rb:28
class RubyLLM::Skills::SkillTool < ::RubyLLM::Tool
  # Initialize with a skill loader.
  #
  # @param loader [Loader] any loader (FilesystemLoader, ZipLoader, etc.)
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill_tool.rb:42
  def initialize(loader); end

  # Dynamic description including available skills.
  #
  # @return [String] tool description with embedded skill metadata
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill_tool.rb:56
  def description; end

  # Execute the tool to load a skill's content or a specific resource.
  #
  # @param command [String] name of skill to load
  # @param arguments [String, nil] optional arguments passed with the command
  # @param resource [String, nil] optional resource path within the skill
  # @return [String] skill content, resource content, or error message
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill_tool.rb:79
  def execute(command:, arguments: T.unsafe(nil), resource: T.unsafe(nil)); end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill_tool.rb:37
  def loader; end

  # Tool name for RubyLLM.
  #
  # @return [String] "skill"
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill_tool.rb:49
  def name; end

  # Convert to RubyLLM Tool-compatible format.
  #
  # @return [Hash] tool definition for RubyLLM
  #
  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill_tool.rb:97
  def to_tool_definition; end

  private

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill_tool.rb:125
  def build_skill_response(skill, arguments: T.unsafe(nil)); end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill_tool.rb:107
  def build_skills_xml; end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill_tool.rb:166
  def escape_xml(text); end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill_tool.rb:200
  def list_available_resources(skill); end

  # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/skill_tool.rb:177
  def load_resource(skill, resource_path); end
end

# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/version.rb:5
RubyLLM::Skills::VERSION = T.let(T.unsafe(nil), String)

# Validates skill structure according to the Agent Skills specification.
#
# Validation rules based on agentskills.io specification:
# - name: required, max 64 chars, lowercase + hyphens only, no leading/trailing hyphens
# - description: required, max 1024 chars
# - license: optional, max 128 chars
# - compatibility: optional, max 500 chars
#
# @example
#   errors = Validator.validate(skill)
#   puts errors # => [] if valid, or list of error messages
#
# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/validator.rb:17
class RubyLLM::Skills::Validator
  class << self
    # Check if a skill is valid.
    #
    # @param skill [Skill] skill to validate
    # @return [Boolean] true if skill passes validation
    #
    # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/validator.rb:43
    def valid?(skill); end

    # Validate a skill and return all errors.
    #
    # @param skill [Skill] skill to validate
    # @return [Array<String>] list of error messages (empty if valid)
    #
    # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/validator.rb:29
    def validate(skill); end

    private

    # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/validator.rb:88
    def validate_compatibility(skill, errors); end

    # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/validator.rb:66
    def validate_description(skill, errors); end

    # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/validator.rb:79
    def validate_license(skill, errors); end

    # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/validator.rb:49
    def validate_name(skill, errors); end

    # pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/validator.rb:97
    def validate_path_name_match(skill, errors); end
  end
end

# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/validator.rb:21
RubyLLM::Skills::Validator::COMPATIBILITY_MAX_LENGTH = T.let(T.unsafe(nil), Integer)

# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/validator.rb:19
RubyLLM::Skills::Validator::DESCRIPTION_MAX_LENGTH = T.let(T.unsafe(nil), Integer)

# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/validator.rb:20
RubyLLM::Skills::Validator::LICENSE_MAX_LENGTH = T.let(T.unsafe(nil), Integer)

# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/validator.rb:18
RubyLLM::Skills::Validator::NAME_MAX_LENGTH = T.let(T.unsafe(nil), Integer)

# pkg:gem/ruby_llm-skills#lib/ruby_llm/skills/validator.rb:22
RubyLLM::Skills::Validator::NAME_PATTERN = T.let(T.unsafe(nil), Regexp)
