# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby-readability` gem.
# Please instead update this file by running `bin/tapioca gem ruby-readability`.


# pkg:gem/ruby-readability#lib/readability.rb:7
module Readability; end

# pkg:gem/ruby-readability#lib/readability.rb:8
class Readability::Document
  # pkg:gem/ruby-readability#lib/readability.rb:42
  def initialize(input, options = T.unsafe(nil)); end

  # Look through the @html document looking for the author
  # Precedence Information here on the wiki: (TODO attach wiki URL if it is accepted)
  # Returns nil if no author is detected
  #
  # pkg:gem/ruby-readability#lib/readability.rb:197
  def author; end

  # pkg:gem/ruby-readability#lib/readability.rb:40
  def best_candidate; end

  # pkg:gem/ruby-readability#lib/readability.rb:40
  def best_candidate=(_arg0); end

  # pkg:gem/ruby-readability#lib/readability.rb:40
  def best_candidate_has_image; end

  # pkg:gem/ruby-readability#lib/readability.rb:40
  def best_candidate_has_image=(_arg0); end

  # pkg:gem/ruby-readability#lib/readability.rb:40
  def candidates; end

  # pkg:gem/ruby-readability#lib/readability.rb:40
  def candidates=(_arg0); end

  # pkg:gem/ruby-readability#lib/readability.rb:373
  def class_weight(e); end

  # pkg:gem/ruby-readability#lib/readability.rb:505
  def clean_conditionally(node, candidates, selector); end

  # pkg:gem/ruby-readability#lib/readability.rb:547
  def clean_conditionally_reason?(name, counts, content_length, options, weight, link_density); end

  # pkg:gem/ruby-readability#lib/readability.rb:306
  def closest_node_with_siblings(element); end

  # pkg:gem/ruby-readability#lib/readability.rb:235
  def content(remove_unlikely_candidates = T.unsafe(nil)); end

  # pkg:gem/ruby-readability#lib/readability.rb:403
  def debug(str); end

  # pkg:gem/ruby-readability#lib/readability.rb:261
  def get_article(candidates, best_candidate); end

  # pkg:gem/ruby-readability#lib/readability.rb:175
  def get_image_size(url); end

  # pkg:gem/ruby-readability#lib/readability.rb:337
  def get_link_density(elem); end

  # pkg:gem/ruby-readability#lib/readability.rb:69
  def handle_exclusions!(whitelist, blacklist); end

  # pkg:gem/ruby-readability#lib/readability.rb:40
  def html; end

  # pkg:gem/ruby-readability#lib/readability.rb:40
  def html=(_arg0); end

  # pkg:gem/ruby-readability#lib/readability.rb:184
  def image_meets_criteria?(image); end

  # pkg:gem/ruby-readability#lib/readability.rb:101
  def images(content = T.unsafe(nil), reload = T.unsafe(nil)); end

  # pkg:gem/ruby-readability#lib/readability.rb:154
  def images_with_fqdn_uris(document = T.unsafe(nil), source_uri); end

  # pkg:gem/ruby-readability#lib/readability.rb:150
  def images_with_fqdn_uris!(source_uri); end

  # pkg:gem/ruby-readability#lib/readability.rb:92
  def make_html(whitelist = T.unsafe(nil), blacklist = T.unsafe(nil)); end

  # pkg:gem/ruby-readability#lib/readability.rb:40
  def options; end

  # pkg:gem/ruby-readability#lib/readability.rb:40
  def options=(_arg0); end

  # pkg:gem/ruby-readability#lib/readability.rb:60
  def prepare_candidates; end

  # pkg:gem/ruby-readability#lib/readability.rb:411
  def remove_unlikely_candidates!; end

  # pkg:gem/ruby-readability#lib/readability.rb:441
  def sanitize(node, candidates, options = T.unsafe(nil)); end

  # pkg:gem/ruby-readability#lib/readability.rb:397
  def score_node(elem); end

  # pkg:gem/ruby-readability#lib/readability.rb:343
  def score_paragraphs(min_text_length); end

  # pkg:gem/ruby-readability#lib/readability.rb:323
  def select_best_candidate(candidates); end

  # pkg:gem/ruby-readability#lib/readability.rb:189
  def title; end

  # pkg:gem/ruby-readability#lib/readability.rb:421
  def transform_misused_divs_into_paragraphs!; end
end

# pkg:gem/ruby-readability#lib/readability.rb:9
Readability::Document::DEFAULT_OPTIONS = T.let(T.unsafe(nil), Hash)

# pkg:gem/ruby-readability#lib/readability.rb:390
Readability::Document::ELEMENT_SCORES = T.let(T.unsafe(nil), Hash)

# pkg:gem/ruby-readability#lib/readability.rb:26
Readability::Document::REGEXES = T.let(T.unsafe(nil), Hash)
