# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `youtube-transcript-rb` gem.
# Please instead update this file by running `bin/tapioca gem youtube-transcript-rb`.


# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/settings.rb:3
module YoutubeRb; end

# Module containing all transcript formatters
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:7
module YoutubeRb::Formatters; end

# Base formatter class. All formatters should inherit from this class
# and implement their own format_transcript and format_transcripts methods.
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:10
class YoutubeRb::Formatters::Formatter
  # Format a single transcript
  #
  # @param transcript [FetchedTranscript] The transcript to format
  # @param options [Hash] Additional formatting options
  # @return [String] The formatted transcript
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:16
  def format_transcript(transcript, **options); end

  # Format multiple transcripts
  #
  # @param transcripts [Array<FetchedTranscript>] The transcripts to format
  # @param options [Hash] Additional formatting options
  # @return [String] The formatted transcripts
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:25
  def format_transcripts(transcripts, **options); end
end

# Utility class to load formatters by type name
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:224
class YoutubeRb::Formatters::FormatterLoader
  # Load a formatter by type name
  #
  # @param formatter_type [String] The formatter type (json, pretty, text, webvtt, srt)
  # @return [Formatter] An instance of the requested formatter
  # @raise [UnknownFormatterType] If the formatter type is not supported
  #
  # @example
  #   loader = FormatterLoader.new
  #   formatter = loader.load("json")
  #   output = formatter.format_transcript(transcript)
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:255
  def load(formatter_type = T.unsafe(nil)); end
end

# Mapping of format names to formatter classes
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:226
YoutubeRb::Formatters::FormatterLoader::TYPES = T.let(T.unsafe(nil), Hash)

# Error raised when an unknown formatter type is requested
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:235
class YoutubeRb::Formatters::FormatterLoader::UnknownFormatterType < ::StandardError
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:236
  def initialize(formatter_type); end
end

# Formats transcript as JSON
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:55
class YoutubeRb::Formatters::JSONFormatter < ::YoutubeRb::Formatters::Formatter
  # Format a single transcript as JSON
  #
  # @param transcript [FetchedTranscript] The transcript to format
  # @param options [Hash] Options passed to JSON.generate (e.g., :indent, :space)
  # @return [String] JSON representation of the transcript
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:61
  def format_transcript(transcript, **options); end

  # Format multiple transcripts as JSON array
  #
  # @param transcripts [Array<FetchedTranscript>] The transcripts to format
  # @param options [Hash] Options passed to JSON.generate
  # @return [String] JSON array representation of the transcripts
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:70
  def format_transcripts(transcripts, **options); end
end

# Formats transcript as pretty-printed Ruby data structures
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:31
class YoutubeRb::Formatters::PrettyPrintFormatter < ::YoutubeRb::Formatters::Formatter
  # Format a single transcript as pretty-printed output
  #
  # @param transcript [FetchedTranscript] The transcript to format
  # @param options [Hash] Options passed to PP.pp
  # @return [String] Pretty-printed transcript data
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:37
  def format_transcript(transcript, **options); end

  # Format multiple transcripts as pretty-printed output
  #
  # @param transcripts [Array<FetchedTranscript>] The transcripts to format
  # @param options [Hash] Options passed to PP.pp
  # @return [String] Pretty-printed transcripts data
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:47
  def format_transcripts(transcripts, **options); end
end

# Formats transcript as SRT (SubRip) subtitle format
#
# @example SRT format
#   1
#   00:00:00,000 --> 00:00:02,500
#   Hello world
#
#   2
#   00:00:02,500 --> 00:00:05,000
#   This is a test
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:180
class YoutubeRb::Formatters::SRTFormatter < ::YoutubeRb::Formatters::TextBasedFormatter
  protected

  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:183
  def format_timestamp(hours, mins, secs, ms); end

  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:187
  def format_transcript_header(lines); end

  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:191
  def format_transcript_helper(index, time_text, snippet); end
end

# Base class for timestamp-based formatters (SRT, WebVTT)
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:98
class YoutubeRb::Formatters::TextBasedFormatter < ::YoutubeRb::Formatters::TextFormatter
  # Format a single transcript with timestamps
  #
  # @param transcript [FetchedTranscript] The transcript to format
  # @param options [Hash] Unused options
  # @return [String] Formatted transcript with timestamps
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:104
  def format_transcript(transcript, **options); end

  protected

  # Format a timestamp from components
  #
  # @param hours [Integer] Hours component
  # @param mins [Integer] Minutes component
  # @param secs [Integer] Seconds component
  # @param ms [Integer] Milliseconds component
  # @return [String] Formatted timestamp
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:130
  def format_timestamp(hours, mins, secs, ms); end

  # Format the transcript header/wrapper
  #
  # @param lines [Array<String>] The formatted lines
  # @return [String] The complete formatted transcript
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:138
  def format_transcript_header(lines); end

  # Format a single transcript entry
  #
  # @param index [Integer] The entry index (0-based)
  # @param time_text [String] The formatted time range
  # @param snippet [TranscriptSnippet] The snippet to format
  # @return [String] The formatted entry
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:148
  def format_transcript_helper(index, time_text, snippet); end

  private

  # Convert seconds to timestamp string
  #
  # @param time [Float] Time in seconds
  # @return [String] Formatted timestamp
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:158
  def seconds_to_timestamp(time); end
end

# Formats transcript as plain text (text only, no timestamps)
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:77
class YoutubeRb::Formatters::TextFormatter < ::YoutubeRb::Formatters::Formatter
  # Format a single transcript as plain text
  #
  # @param transcript [FetchedTranscript] The transcript to format
  # @param options [Hash] Unused options
  # @return [String] Plain text with each line separated by newlines
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:83
  def format_transcript(transcript, **options); end

  # Format multiple transcripts as plain text
  #
  # @param transcripts [Array<FetchedTranscript>] The transcripts to format
  # @param options [Hash] Unused options
  # @return [String] Plain text with transcripts separated by triple newlines
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:92
  def format_transcripts(transcripts, **options); end
end

# Formats transcript as WebVTT (Web Video Text Tracks) format
#
# @example WebVTT format
#   WEBVTT
#
#   00:00:00.000 --> 00:00:02.500
#   Hello world
#
#   00:00:02.500 --> 00:00:05.000
#   This is a test
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:207
class YoutubeRb::Formatters::WebVTTFormatter < ::YoutubeRb::Formatters::TextBasedFormatter
  protected

  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:210
  def format_timestamp(hours, mins, secs, ms); end

  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:214
  def format_transcript_header(lines); end

  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/formatters.rb:218
  def format_transcript_helper(index, time_text, snippet); end
end

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/settings.rb:4
module YoutubeRb::Transcript
  class << self
    # Convenience method to fetch a transcript
    # @param video_id [String] YouTube video ID
    # @param languages [Array<String>] Language codes in order of preference
    # @param preserve_formatting [Boolean] Whether to preserve HTML formatting
    # @return [FetchedTranscript] The fetched transcript
    #
    # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript.rb:19
    def fetch(video_id, languages: T.unsafe(nil), preserve_formatting: T.unsafe(nil)); end

    # Convenience method to list available transcripts
    # @param video_id [String] YouTube video ID
    # @return [TranscriptList] List of available transcripts
    #
    # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript.rb:27
    def list(video_id); end
  end
end

# Raised when a video is age restricted
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:154
class YoutubeRb::Transcript::AgeRestricted < ::YoutubeRb::Transcript::CouldNotRetrieveTranscript; end

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:155
YoutubeRb::Transcript::AgeRestricted::CAUSE_MESSAGE = T.let(T.unsafe(nil), String)

# Raised when a transcript could not be retrieved
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:9
class YoutubeRb::Transcript::CouldNotRetrieveTranscript < ::YoutubeRb::Transcript::Error
  # @param video_id [String] the YouTube video ID
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:16
  def initialize(video_id); end

  # @return [String] the cause of the error
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:22
  def cause_message; end

  # @return [String] the video ID that caused the error
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:13
  def video_id; end

  private

  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:28
  def build_error_message; end

  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:40
  def github_referral; end
end

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:10
YoutubeRb::Transcript::CouldNotRetrieveTranscript::WATCH_URL = T.let(T.unsafe(nil), String)

# Base error class for all YouTube Transcript errors
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:6
class YoutubeRb::Transcript::Error < ::StandardError; end

# Raised when consent cookie creation fails
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:172
class YoutubeRb::Transcript::FailedToCreateConsentCookie < ::YoutubeRb::Transcript::CouldNotRetrieveTranscript; end

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:173
YoutubeRb::Transcript::FailedToCreateConsentCookie::CAUSE_MESSAGE = T.let(T.unsafe(nil), String)

# Represents a fetched transcript containing multiple snippets
# This class is Enumerable, allowing iteration over snippets
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:54
class YoutubeRb::Transcript::FetchedTranscript
  include ::Enumerable

  # @param video_id [String] the YouTube video ID
  # @param language [String] the language name
  # @param language_code [String] the language code
  # @param is_generated [Boolean] whether auto-generated
  # @param snippets [Array<TranscriptSnippet>] the snippets (optional)
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:77
  def initialize(video_id:, language:, language_code:, is_generated:, snippets: T.unsafe(nil)); end

  # Get a snippet by index
  # @param index [Integer] the index
  # @return [TranscriptSnippet] the snippet at the given index
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:102
  def [](index); end

  # Add a snippet to the transcript
  # @param snippet [TranscriptSnippet] the snippet to add
  # @return [self]
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:88
  def add_snippet(snippet); end

  # Iterate over each snippet
  # @yield [TranscriptSnippet] each snippet in the transcript
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:95
  def each(&_arg0); end

  # Check if transcript was auto-generated
  # @return [Boolean]
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:121
  def generated?; end

  # @return [Boolean] whether the transcript was auto-generated
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:67
  def is_generated; end

  # @return [String] the language name (e.g., "English")
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:61
  def language; end

  # @return [String] the language code (e.g., "en")
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:64
  def language_code; end

  # Get the number of snippets
  # @return [Integer] the count of snippets
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:108
  def length; end

  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:111
  def size; end

  # @return [Array<TranscriptSnippet>] the transcript snippets
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:70
  def snippets; end

  # Convert to raw data (array of hashes)
  # @return [Array<Hash>] array of snippet hashes
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:115
  def to_raw_data; end

  # @return [String] the video ID
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:58
  def video_id; end
end

# YouTube Innertube API URL template
# @example
#   format(INNERTUBE_API_URL, api_key: "key123")
#   # => "https://www.youtube.com/youtubei/v1/player?key=key123"
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/settings.rb:15
YoutubeRb::Transcript::INNERTUBE_API_URL = T.let(T.unsafe(nil), String)

# Innertube API context for Android client
# Used in POST requests to the Innertube API
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/settings.rb:19
YoutubeRb::Transcript::INNERTUBE_CONTEXT = T.let(T.unsafe(nil), Hash)

# Raised when an invalid video ID is provided
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:112
class YoutubeRb::Transcript::InvalidVideoId < ::YoutubeRb::Transcript::CouldNotRetrieveTranscript; end

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:113
YoutubeRb::Transcript::InvalidVideoId::CAUSE_MESSAGE = T.let(T.unsafe(nil), String)

# Raised when YouTube blocks the IP specifically
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:138
class YoutubeRb::Transcript::IpBlocked < ::YoutubeRb::Transcript::RequestBlocked; end

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:139
YoutubeRb::Transcript::IpBlocked::CAUSE_MESSAGE = T.let(T.unsafe(nil), String)

# Raised when no transcripts are available for a video
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:205
class YoutubeRb::Transcript::NoTranscriptAvailable < ::YoutubeRb::Transcript::CouldNotRetrieveTranscript; end

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:206
YoutubeRb::Transcript::NoTranscriptAvailable::CAUSE_MESSAGE = T.let(T.unsafe(nil), String)

# Raised when no transcript is found for the requested languages
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:177
class YoutubeRb::Transcript::NoTranscriptFound < ::YoutubeRb::Transcript::CouldNotRetrieveTranscript
  # @param video_id [String] the YouTube video ID
  # @param requested_language_codes [Array<String>] the language codes that were requested
  # @param transcript_data [Object] the TranscriptList object with available transcripts
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:189
  def initialize(video_id, requested_language_codes, transcript_data); end

  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:195
  def cause_message; end

  # @return [Array<String>] the requested language codes
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:181
  def requested_language_codes; end

  # @return [Object] the transcript data (TranscriptList)
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:184
  def transcript_data; end
end

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:178
YoutubeRb::Transcript::NoTranscriptFound::CAUSE_MESSAGE = T.let(T.unsafe(nil), String)

# Raised when a transcript is not translatable
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:162
class YoutubeRb::Transcript::NotTranslatable < ::YoutubeRb::Transcript::CouldNotRetrieveTranscript; end

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:163
YoutubeRb::Transcript::NotTranslatable::CAUSE_MESSAGE = T.let(T.unsafe(nil), String)

# Reason messages for playability failures
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list_fetcher.rb:16
module YoutubeRb::Transcript::PlayabilityFailedReason; end

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list_fetcher.rb:18
YoutubeRb::Transcript::PlayabilityFailedReason::AGE_RESTRICTED = T.let(T.unsafe(nil), String)

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list_fetcher.rb:17
YoutubeRb::Transcript::PlayabilityFailedReason::BOT_DETECTED = T.let(T.unsafe(nil), String)

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list_fetcher.rb:19
YoutubeRb::Transcript::PlayabilityFailedReason::VIDEO_UNAVAILABLE = T.let(T.unsafe(nil), String)

# Playability status values returned by YouTube
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list_fetcher.rb:9
module YoutubeRb::Transcript::PlayabilityStatus; end

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list_fetcher.rb:11
YoutubeRb::Transcript::PlayabilityStatus::ERROR = T.let(T.unsafe(nil), String)

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list_fetcher.rb:12
YoutubeRb::Transcript::PlayabilityStatus::LOGIN_REQUIRED = T.let(T.unsafe(nil), String)

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list_fetcher.rb:10
YoutubeRb::Transcript::PlayabilityStatus::OK = T.let(T.unsafe(nil), String)

# Raised when a PO token is required to fetch the transcript
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:210
class YoutubeRb::Transcript::PoTokenRequired < ::YoutubeRb::Transcript::CouldNotRetrieveTranscript; end

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:211
YoutubeRb::Transcript::PoTokenRequired::CAUSE_MESSAGE = T.let(T.unsafe(nil), String)

# Raised when YouTube blocks the request
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:120
class YoutubeRb::Transcript::RequestBlocked < ::YoutubeRb::Transcript::CouldNotRetrieveTranscript; end

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:121
YoutubeRb::Transcript::RequestBlocked::BASE_CAUSE_MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:128
YoutubeRb::Transcript::RequestBlocked::CAUSE_MESSAGE = T.let(T.unsafe(nil), String)

# Raised when too many requests are made (HTTP 429)
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:144
class YoutubeRb::Transcript::TooManyRequests < ::YoutubeRb::Transcript::CouldNotRetrieveTranscript; end

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:145
YoutubeRb::Transcript::TooManyRequests::CAUSE_MESSAGE = T.let(T.unsafe(nil), String)

# Represents a list of available transcripts for a YouTube video.
# This class is Enumerable, allowing iteration over all available transcripts.
# It provides functionality to search for transcripts in specific languages.
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list.rb:8
class YoutubeRb::Transcript::TranscriptList
  include ::Enumerable

  # @param video_id [String] the YouTube video ID
  # @param manually_created_transcripts [Hash<String, TranscriptMetadata>] manually created transcripts by language code
  # @param generated_transcripts [Hash<String, TranscriptMetadata>] auto-generated transcripts by language code
  # @param translation_languages [Array<TranslationLanguage>] available translation languages
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list.rb:61
  def initialize(video_id:, manually_created_transcripts:, generated_transcripts:, translation_languages:); end

  # Iterate over all transcripts (manually created first, then generated)
  #
  # @yield [TranscriptMetadata] each available transcript
  # @return [Enumerator] if no block given
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list.rb:72
  def each(&_arg0); end

  # Find an automatically generated transcript for the given language codes.
  #
  # @param language_codes [Array<String>] language codes in descending priority
  # @return [TranscriptMetadata] the found transcript
  # @raise [NoTranscriptFound] if no generated transcript matches
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list.rb:97
  def find_generated_transcript(language_codes); end

  # Find a manually created transcript for the given language codes.
  #
  # @param language_codes [Array<String>] language codes in descending priority
  # @return [TranscriptMetadata] the found transcript
  # @raise [NoTranscriptFound] if no manually created transcript matches
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list.rb:106
  def find_manually_created_transcript(language_codes); end

  # Find a transcript for the given language codes.
  # Manually created transcripts are preferred over generated ones.
  #
  # @param language_codes [Array<String>] language codes in descending priority
  # @return [TranscriptMetadata] the found transcript
  # @raise [NoTranscriptFound] if no transcript matches the requested languages
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list.rb:85
  def find_transcript(language_codes); end

  # String representation of the transcript list
  #
  # @return [String] human-readable description of available transcripts
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list.rb:113
  def to_s; end

  # @return [String] the video ID this TranscriptList is for
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list.rb:12
  def video_id; end

  private

  # Find a transcript from the given dictionaries
  #
  # @param language_codes [Array<String>] language codes to search for
  # @param transcript_dicts [Array<Hash>] transcript dictionaries to search
  # @return [TranscriptMetadata] the found transcript
  # @raise [NoTranscriptFound] if no transcript matches
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list.rb:136
  def find_transcript_in(language_codes, transcript_dicts); end

  # Format a list of transcripts for display
  #
  # @param transcripts [Array<TranscriptMetadata>] transcripts to format
  # @return [String] formatted list or "None"
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list.rb:150
  def format_language_list(transcripts); end

  # Format translation languages for display
  #
  # @return [String] formatted list or "None"
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list.rb:159
  def format_translation_languages; end

  class << self
    # Build a TranscriptList from captions JSON data
    #
    # @param http_client [Faraday::Connection] the HTTP client for fetching transcripts
    # @param video_id [String] the YouTube video ID
    # @param captions_json [Hash] the captions JSON parsed from YouTube
    # @return [TranscriptList] the created TranscriptList
    #
    # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list.rb:20
    def build(http_client:, video_id:, captions_json:); end
  end
end

# Fetches transcript lists from YouTube videos.
# This class handles all the HTTP communication with YouTube,
# including consent cookie handling and error detection.
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list_fetcher.rb:25
class YoutubeRb::Transcript::TranscriptListFetcher
  # @param http_client [Faraday::Connection] the HTTP client to use
  # @param proxy_config [Object, nil] optional proxy configuration
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list_fetcher.rb:28
  def initialize(http_client:, proxy_config: T.unsafe(nil)); end

  # Fetch the transcript list for a video
  #
  # @param video_id [String] the YouTube video ID
  # @return [TranscriptList] the list of available transcripts
  # @raise [CouldNotRetrieveTranscript] if transcripts cannot be retrieved
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list_fetcher.rb:38
  def fetch(video_id); end

  private

  # Assert that the video is playable
  #
  # @param playability_status_data [Hash, nil] the playability status from API
  # @param video_id [String] the video ID
  # @raise [Various] depending on the playability status
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list_fetcher.rb:105
  def assert_playability(playability_status_data, video_id); end

  # Create a consent cookie from the HTML
  #
  # @param html [String] the HTML content
  # @param video_id [String] the video ID
  # @raise [FailedToCreateConsentCookie] if the cookie cannot be created
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list_fetcher.rb:139
  def create_consent_cookie(html, video_id); end

  # Extract captions JSON from innertube data
  #
  # @param innertube_data [Hash] the innertube API response
  # @param video_id [String] the video ID
  # @return [Hash] the captions JSON
  # @raise [TranscriptsDisabled] if no captions are available
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list_fetcher.rb:91
  def extract_captions_json(innertube_data, video_id); end

  # Extract the INNERTUBE_API_KEY from the video page HTML
  #
  # @param html [String] the HTML content
  # @param video_id [String] the video ID (for error messages)
  # @return [String] the API key
  # @raise [IpBlocked] if a CAPTCHA is detected
  # @raise [YouTubeDataUnparsable] if the key cannot be found
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list_fetcher.rb:76
  def extract_innertube_api_key(html, video_id); end

  # Fetch captions JSON with retry support
  #
  # @param video_id [String] the YouTube video ID
  # @param try_number [Integer] current retry attempt
  # @return [Hash] the captions JSON
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list_fetcher.rb:53
  def fetch_captions_json(video_id, try_number: T.unsafe(nil)); end

  # Fetch raw HTML from YouTube
  #
  # @param video_id [String] the video ID
  # @return [String] the HTML content (unescaped)
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list_fetcher.rb:169
  def fetch_html(video_id); end

  # Fetch data from the Innertube API
  #
  # @param video_id [String] the video ID
  # @param api_key [String] the API key
  # @return [Hash] the API response
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list_fetcher.rb:189
  def fetch_innertube_data(video_id, api_key); end

  # Fetch the video HTML page
  #
  # @param video_id [String] the video ID
  # @return [String] the HTML content
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list_fetcher.rb:153
  def fetch_video_html(video_id); end

  # Raise appropriate errors for HTTP responses
  #
  # @param response [Faraday::Response] the HTTP response
  # @param video_id [String] the video ID
  # @raise [IpBlocked] for 429 responses
  # @raise [YouTubeRequestFailed] for other error responses
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_list_fetcher.rb:210
  def raise_http_errors(response, video_id); end
end

# Represents transcript metadata and provides fetch/translate capabilities
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:127
class YoutubeRb::Transcript::TranscriptMetadata
  # @param http_client [Faraday::Connection] the HTTP client
  # @param video_id [String] the YouTube video ID
  # @param url [String] the transcript URL
  # @param language [String] the language name
  # @param language_code [String] the language code
  # @param is_generated [Boolean] whether auto-generated
  # @param translation_languages [Array<TranslationLanguage>] available translations
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:150
  def initialize(http_client:, video_id:, url:, language:, language_code:, is_generated:, translation_languages:); end

  # Fetch the actual transcript data
  # @param preserve_formatting [Boolean] whether to preserve HTML formatting
  # @return [FetchedTranscript] the fetched transcript
  # @raise [PoTokenRequired] if a PO token is required
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:167
  def fetch(preserve_formatting: T.unsafe(nil)); end

  # Check if transcript was auto-generated
  # @return [Boolean]
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:214
  def generated?; end

  # @return [Boolean] whether auto-generated
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:138
  def is_generated; end

  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:190
  def is_translatable; end

  # @return [String] the language name
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:132
  def language; end

  # @return [String] the language code
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:135
  def language_code; end

  # String representation of the transcript
  # @return [String]
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:220
  def to_s; end

  # Check if this transcript can be translated
  # @return [Boolean]
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:187
  def translatable?; end

  # Translate this transcript to another language
  # @param language_code [String] the target language code
  # @return [TranscriptMetadata] a new TranscriptMetadata object for the translated version
  # @raise [NotTranslatable] if the transcript cannot be translated
  # @raise [TranslationLanguageNotAvailable] if the language is not available
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:197
  def translate(language_code); end

  # @return [Array<TranslationLanguage>] available translation languages
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:141
  def translation_languages; end

  # @return [String] the video ID
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:129
  def video_id; end

  private

  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:227
  def raise_http_errors(response); end
end

# Parses XML transcript data from YouTube
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_parser.rb:9
class YoutubeRb::Transcript::TranscriptParser
  # @param preserve_formatting [Boolean] whether to preserve HTML formatting tags
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_parser.rb:25
  def initialize(preserve_formatting: T.unsafe(nil)); end

  # Parse XML transcript data into TranscriptSnippet objects
  # @param raw_data [String] the raw XML data from YouTube
  # @return [Array<TranscriptSnippet>] parsed transcript snippets
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_parser.rb:33
  def parse(raw_data); end

  private

  # Build regex for removing HTML tags
  # @return [Regexp]
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_parser.rb:58
  def build_html_regex; end

  # Process text by unescaping HTML entities and removing unwanted tags
  # @param text [String] the raw text
  # @return [String] processed text
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_parser.rb:73
  def process_text(text); end
end

# HTML formatting tags to preserve when preserve_formatting is enabled
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript_parser.rb:11
YoutubeRb::Transcript::TranscriptParser::FORMATTING_TAGS = T.let(T.unsafe(nil), Array)

# Represents a single transcript snippet/segment
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:22
class YoutubeRb::Transcript::TranscriptSnippet
  # @param text [String] the text content
  # @param start [Float] the start time in seconds
  # @param duration [Float] the duration in seconds
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:35
  def initialize(text:, start:, duration:); end

  # @return [Float] the duration in seconds
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:30
  def duration; end

  # @return [Float] the start time in seconds
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:27
  def start; end

  # @return [String] the text content of the snippet
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:24
  def text; end

  # Convert to hash representation
  # @return [Hash] hash with text, start, and duration keys
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:43
  def to_h; end
end

# Raised when transcripts are disabled for a video
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:149
class YoutubeRb::Transcript::TranscriptsDisabled < ::YoutubeRb::Transcript::CouldNotRetrieveTranscript; end

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:150
YoutubeRb::Transcript::TranscriptsDisabled::CAUSE_MESSAGE = T.let(T.unsafe(nil), String)

# Represents a language available for translation
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:6
class YoutubeRb::Transcript::TranslationLanguage
  # @param language [String] the language name
  # @param language_code [String] the language code
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:15
  def initialize(language:, language_code:); end

  # @return [String] the language name (e.g., "Spanish")
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:8
  def language; end

  # @return [String] the language code (e.g., "es")
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/transcript.rb:11
  def language_code; end
end

# Raised when the requested translation language is not available
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:167
class YoutubeRb::Transcript::TranslationLanguageNotAvailable < ::YoutubeRb::Transcript::CouldNotRetrieveTranscript; end

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:168
YoutubeRb::Transcript::TranslationLanguageNotAvailable::CAUSE_MESSAGE = T.let(T.unsafe(nil), String)

# Raised when a video is unavailable
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:107
class YoutubeRb::Transcript::VideoUnavailable < ::YoutubeRb::Transcript::CouldNotRetrieveTranscript; end

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:108
YoutubeRb::Transcript::VideoUnavailable::CAUSE_MESSAGE = T.let(T.unsafe(nil), String)

# Raised when a video is unplayable
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:76
class YoutubeRb::Transcript::VideoUnplayable < ::YoutubeRb::Transcript::CouldNotRetrieveTranscript
  # @param video_id [String] the YouTube video ID
  # @param reason [String, nil] the reason the video is unplayable
  # @param sub_reasons [Array<String>] additional details
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:88
  def initialize(video_id, reason = T.unsafe(nil), sub_reasons = T.unsafe(nil)); end

  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:94
  def cause_message; end

  # @return [String, nil] the reason the video is unplayable
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:80
  def reason; end

  # @return [Array<String>] additional sub-reasons
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:83
  def sub_reasons; end
end

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:77
YoutubeRb::Transcript::VideoUnplayable::CAUSE_MESSAGE = T.let(T.unsafe(nil), String)

# YouTube watch URL template
# @example
#   format(WATCH_URL, video_id: "abc123")
#   # => "https://www.youtube.com/watch?v=abc123"
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/settings.rb:9
YoutubeRb::Transcript::WATCH_URL = T.let(T.unsafe(nil), String)

# Raised when YouTube data cannot be parsed
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:51
class YoutubeRb::Transcript::YouTubeDataUnparsable < ::YoutubeRb::Transcript::CouldNotRetrieveTranscript; end

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:52
YoutubeRb::Transcript::YouTubeDataUnparsable::CAUSE_MESSAGE = T.let(T.unsafe(nil), String)

# Raised when a request to YouTube fails
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:57
class YoutubeRb::Transcript::YouTubeRequestFailed < ::YoutubeRb::Transcript::CouldNotRetrieveTranscript
  # @param video_id [String] the YouTube video ID
  # @param http_error [StandardError] the HTTP error that occurred
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:65
  def initialize(video_id, http_error); end

  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:70
  def cause_message; end

  # @return [String] the reason for the failure
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:61
  def reason; end
end

# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/errors.rb:58
YoutubeRb::Transcript::YouTubeRequestFailed::CAUSE_MESSAGE = T.let(T.unsafe(nil), String)

# Main entry point for fetching YouTube transcripts.
# This class provides a simple API for retrieving transcripts from YouTube videos.
#
# @example Basic usage
#   api = YoutubeRb::Transcript::YouTubeTranscriptApi.new
#   transcript = api.fetch("dQw4w9WgXcQ")
#   transcript.each { |snippet| puts snippet.text }
#
# @example With language preference
#   api = YoutubeRb::Transcript::YouTubeTranscriptApi.new
#   transcript = api.fetch("dQw4w9WgXcQ", languages: ["es", "en"])
#
# @example Listing available transcripts
#   api = YoutubeRb::Transcript::YouTubeTranscriptApi.new
#   transcript_list = api.list("dQw4w9WgXcQ")
#   transcript_list.each { |t| puts t }
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/api.rb:25
class YoutubeRb::Transcript::YouTubeTranscriptApi
  # @param http_client [Faraday::Connection, nil] Custom HTTP client (optional)
  # @param proxy_config [Object, nil] Proxy configuration (optional)
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/api.rb:31
  def initialize(http_client: T.unsafe(nil), proxy_config: T.unsafe(nil)); end

  # Fetch a transcript for a video.
  # This is a convenience method that combines `list` and `find_transcript`.
  #
  # @param video_id [String] The YouTube video ID
  # @param languages [Array<String>] Language codes in order of preference (default: ["en"])
  # @param preserve_formatting [Boolean] Whether to preserve HTML formatting (default: false)
  # @return [FetchedTranscript] The fetched transcript
  # @raise [NoTranscriptFound] If no transcript matches the requested languages
  # @raise [TranscriptsDisabled] If transcripts are disabled for the video
  # @raise [VideoUnavailable] If the video is not available
  #
  # @example
  #   api = YouTubeTranscriptApi.new
  #   transcript = api.fetch("dQw4w9WgXcQ", languages: ["en", "es"])
  #   puts transcript.first.text
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/api.rb:56
  def fetch(video_id, languages: T.unsafe(nil), preserve_formatting: T.unsafe(nil)); end

  # Fetch transcripts for multiple videos.
  #
  # @param video_ids [Array<String>] Array of YouTube video IDs
  # @param languages [Array<String>] Language codes in order of preference (default: ["en"])
  # @param preserve_formatting [Boolean] Whether to preserve HTML formatting (default: false)
  # @param continue_on_error [Boolean] Whether to continue if a video fails (default: false)
  # @yield [video_id, result] Block called for each video with either transcript or error
  # @yieldparam video_id [String] The video ID being processed
  # @yieldparam result [FetchedTranscript, StandardError] The transcript or error
  # @return [Hash<String, FetchedTranscript>] Hash mapping video IDs to transcripts
  # @raise [CouldNotRetrieveTranscript] If any video fails and continue_on_error is false
  #
  # @example Fetch multiple videos
  #   api = YouTubeTranscriptApi.new
  #   transcripts = api.fetch_all(["video1", "video2", "video3"])
  #   transcripts.each { |id, t| puts "#{id}: #{t.length} snippets" }
  #
  # @example With error handling
  #   api = YouTubeTranscriptApi.new
  #   api.fetch_all(["video1", "video2"], continue_on_error: true) do |video_id, result|
  #     if result.is_a?(StandardError)
  #       puts "Error for #{video_id}: #{result.message}"
  #     else
  #       puts "Got #{result.length} snippets for #{video_id}"
  #     end
  #   end
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/api.rb:112
  def fetch_all(video_ids, languages: T.unsafe(nil), preserve_formatting: T.unsafe(nil), continue_on_error: T.unsafe(nil)); end

  # List all available transcripts for a video.
  #
  # @param video_id [String] The YouTube video ID
  # @return [TranscriptList] A list of available transcripts
  # @raise [TranscriptsDisabled] If transcripts are disabled for the video
  # @raise [VideoUnavailable] If the video is not available
  #
  # @example
  #   api = YouTubeTranscriptApi.new
  #   transcript_list = api.list("dQw4w9WgXcQ")
  #
  #   # Find a specific transcript
  #   transcript = transcript_list.find_transcript(["en"])
  #
  #   # Or iterate over all available transcripts
  #   transcript_list.each do |transcript|
  #     puts "#{transcript.language_code}: #{transcript.language}"
  #   end
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/api.rb:81
  def list(video_id); end

  private

  # Build the default Faraday HTTP client
  #
  # @return [Faraday::Connection] The configured HTTP client
  #
  # pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/api.rb:133
  def build_default_http_client; end
end

# Default timeout for HTTP requests in seconds
#
# pkg:gem/youtube-transcript-rb#lib/youtube_rb/transcript/api.rb:27
YoutubeRb::Transcript::YouTubeTranscriptApi::DEFAULT_TIMEOUT = T.let(T.unsafe(nil), Integer)
