# frozen_string_literal: true

require "fileutils"
require "json"
require "yaml"

require_relative "../quality/coverage_parser"
require_relative "../quality/flog_parser"
require_relative "../quality/rubocop_parser"
require_relative "../quality/mutant_parser"
require_relative "../quality/report"

QUALITY_DIR = Rails.root.join("tmp/quality")
MUTANT_SUBJECTS = %w[*].freeze

namespace :quality do
  task :setup do
    FileUtils.mkdir_p(QUALITY_DIR)
  end

  desc "Run Rubocop metrics and parse results"
  task rubocop: :setup do
    json_path = QUALITY_DIR.join("rubocop.json")
    cops = %w[
      Metrics/ClassLength
      Metrics/ModuleLength
      Metrics/MethodLength
      Metrics/AbcSize
      Metrics/CyclomaticComplexity
      Metrics/PerceivedComplexity
    ].join(",")

    sh "bundle exec rubocop --format json --only #{cops} > #{json_path} 2>&1 || true"

    parser = Quality::RubocopParser.new(json_path)
    result = parser.parse
    File.write(QUALITY_DIR.join("rubocop_metrics.json"), JSON.pretty_generate(result))
  end

  desc "Run Flog and parse results"
  task flog: :setup do
    parser = Quality::FlogParser.new(%w[app lib/quality])
    result = parser.parse
    File.write(QUALITY_DIR.join("flog.json"), JSON.pretty_generate(result))
  end

  desc "Run Mutant and parse results"
  task mutation: :setup do
    txt_path = QUALITY_DIR.join("mutation.txt")

    cmd = [
      "bundle", "exec", "mutant", "run",
      "--integration", "minitest",
      "--include", "test",
      "--include", "lib",
      "--require", "./script/mutant_bootstrap.rb",
      "--usage", "opensource",
      "--", *MUTANT_SUBJECTS
    ]
    sh "#{cmd.shelljoin} > #{txt_path.to_s.shellescape} 2>&1 || true"

    begin
      parser = Quality::MutantParser.new(txt_path)
      result = parser.parse
      File.write(QUALITY_DIR.join("mutation.json"), JSON.pretty_generate(result))
      ratchet_if_unset!(result[:kill_ratio], result[:mutations])
    rescue Quality::MutantParser::ParseError => e
      puts "[quality:mutation] #{e.message}"
      File.write(QUALITY_DIR.join("mutation.json"), JSON.pretty_generate({ kill_ratio: nil }))
    end
  end
end

desc "Run all quality gates (runs tests first, then metrics)"
task quality: :test do
  Rake::Task["quality:setup"].invoke
  Rake::Task["quality:rubocop"].invoke
  Rake::Task["quality:flog"].invoke
  Rake::Task["quality:mutation"].invoke

  measurements = {}

  # Coverage (generated by test task via SimpleCov)
  coverage_path = Rails.root.join("coverage/.last_run.json")
  if coverage_path.exist?
    measurements[:coverage] = Quality::CoverageParser.new(coverage_path).parse
  end

  # Rubocop
  rubocop_path = QUALITY_DIR.join("rubocop_metrics.json")
  if rubocop_path.exist?
    measurements.merge!(JSON.parse(File.read(rubocop_path), symbolize_names: true))
  end

  # Flog
  flog_path = QUALITY_DIR.join("flog.json")
  if flog_path.exist?
    measurements[:flog] = JSON.parse(File.read(flog_path), symbolize_names: true)
  end

  # Mutation
  mutation_path = QUALITY_DIR.join("mutation.json")
  if mutation_path.exist?
    measurements[:mutation] = JSON.parse(File.read(mutation_path), symbolize_names: true)
  end

  thresholds = YAML.load_file(Rails.root.join("config/quality_thresholds.yml"))
  report = Quality::Report.new(measurements: measurements, thresholds: thresholds)

  puts report
  exit(report.passed? ? 0 : 1)
end

def ratchet_if_unset!(kill_ratio, mutations = 0)
  return if mutations.zero?

  path = Rails.root.join("config/quality_thresholds.yml")
  thresholds = YAML.load_file(path)

  return unless thresholds.dig("mutation", "kill_ratio_min").nil?

  thresholds["mutation"] ||= {}
  thresholds["mutation"]["kill_ratio_min"] = kill_ratio
  File.write(path, thresholds.to_yaml)
  puts "[quality:mutation] Ratchet set: mutation.kill_ratio_min = #{kill_ratio}"
end
