# frozen_string_literal: true
# rbs_inline: disabled

require "fileutils"
require "json"
require "yaml"

require_relative "../quality/coverage_parser"
require_relative "../quality/coverage_snapshot"
require_relative "../quality/flog_parser"
require_relative "../quality/rubocop_parser"
require_relative "../quality/sorbet_coverage_parser"
require_relative "../quality/report"

QUALITY_DIR = Rails.root.join("tmp/quality")

namespace :quality do
  task :setup do
    FileUtils.mkdir_p(QUALITY_DIR)
  end

  desc "Run Rubocop metrics and parse results"
  task rubocop: :setup do
    json_path = QUALITY_DIR.join("rubocop.json")
    cops = %w[
      Metrics/ClassLength
      Metrics/ModuleLength
      Metrics/MethodLength
      Metrics/AbcSize
      Metrics/CyclomaticComplexity
      Metrics/PerceivedComplexity
    ].join(",")

    sh "bundle exec rubocop --format json --only #{cops} > #{json_path} 2>&1 || true"

    parser = Quality::RubocopParser.new(json_path)
    result = parser.parse
    File.write(QUALITY_DIR.join("rubocop_metrics.json"), JSON.pretty_generate(result))
  end

  desc "Run Flog and parse results"
  task flog: :setup do
    parser = Quality::FlogParser.new(%w[app lib/quality])
    result = parser.parse
    File.write(QUALITY_DIR.join("flog.json"), JSON.pretty_generate(result))
  end

  desc "Measure Sorbet type coverage and parse results"
  task sorbet: :setup do
    snapshot_path = QUALITY_DIR.join("sorbet_snapshot.json")

    # spoom's `srb coverage snapshot` prints a human table with no machine
    # format, so drive the library directly -- `Snapshot#to_json` is the same
    # data the CLI formats. It shells out to `srb tc` internally, which takes
    # a few seconds.
    #
    # `|| true` like the rubocop task above: the run is informational and a
    # non-zero `srb tc` is CI's job to report, not this task's.
    sh "bundle exec ruby -r spoom -e " \
       "'File.write(ARGV[0], Spoom::Coverage.snapshot(Spoom::Context.new(Dir.pwd)).to_json)' " \
       "#{snapshot_path} || true"

    parser = Quality::SorbetCoverageParser.new(snapshot_path)
    result = parser.parse

    # `|| true` above means a broken run reaches here as an empty result,
    # which the report would silently omit -- indistinguishable from "not
    # measured yet". Say so out loud instead.
    warn "[quality:sorbet] no snapshot parsed from #{snapshot_path}; type coverage will be missing from the report" if result.empty?

    File.write(QUALITY_DIR.join("sorbet_coverage.json"), JSON.pretty_generate(result))
  end
end

desc "Run all quality gates"
task quality: "quality:setup" do
  Rake::Task["quality:rubocop"].invoke
  Rake::Task["quality:flog"].invoke
  Rake::Task["quality:sorbet"].invoke

  measurements = {}

  # Coverage (generated by test task via SimpleCov)
  coverage_path = Quality::CoverageSnapshot.preferred_path(Rails.root)
  if coverage_path.exist?
    measurements[:coverage] = Quality::CoverageParser.new(coverage_path).parse
  end

  # Rubocop
  rubocop_path = QUALITY_DIR.join("rubocop_metrics.json")
  if rubocop_path.exist?
    measurements.merge!(JSON.parse(File.read(rubocop_path), symbolize_names: true))
  end

  # Flog
  flog_path = QUALITY_DIR.join("flog.json")
  if flog_path.exist?
    measurements[:flog] = JSON.parse(File.read(flog_path), symbolize_names: true)
  end

  # Sorbet type coverage (informational -- see Report::INFO_METRICS)
  sorbet_path = QUALITY_DIR.join("sorbet_coverage.json")
  if sorbet_path.exist?
    measurements[:sorbet] = JSON.parse(File.read(sorbet_path), symbolize_names: true)
  end

  thresholds = YAML.load_file(Rails.root.join("config/quality_thresholds.yml"))
  report = Quality::Report.new(measurements: measurements, thresholds: thresholds)

  puts report
  exit(report.passed? ? 0 : 1)
end
