# Omakase Ruby styling for Rails
inherit_gem: {rubocop-rails-omakase: rubocop.yml}

inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rbs_inline
  - rubocop-minitest

AllCops:
  RubyInterpreters:
    - ruby
    - rake
  NewCops: enable
  TargetRubyVersion: 4.0
  TargetRailsVersion: 8.1
  Exclude:
    - "app/components/**/*"
    - "app/views/**/*"
    - "config/**/*"

Layout/LeadingCommentSpace:
  Enabled: false

Bundler/OrderedGems:
  Enabled: true

Metrics/ClassLength:
  Enabled: true
  Max: 100
  Exclude:
    - "test/**/*"
    - "db/**/*"
    - "spec/**/*"

Metrics/ModuleLength:
  Enabled: true
  Max: 100
  Exclude:
    - "test/**/*"
    - "db/**/*"
    - "spec/**/*"

Metrics/MethodLength:
  Enabled: true
  Max: 15
  Exclude:
    - "test/**/*"
    - "db/**/*"
    - "db/migrate/**/*"

Metrics/AbcSize:
  Enabled: true
  Max: 15
  Exclude:
    - "test/**/*"
    - "db/**/*"

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 6
  Exclude:
    - "test/**/*"
    - "db/**/*"

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 7
  Exclude:
    - "test/**/*"
    - "db/**/*"
