# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

inherit_from: .rubocop_todo.yml

AllCops:
  RubyInterpreters:
    - ruby
    - rake
  NewCops: enable
  TargetRubyVersion: 4.0
  TargetRailsVersion: 8.1

Layout/LeadingCommentSpace:
  Enabled: false
