# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Components::Home`.
# Please instead update this file by running `bin/tapioca dsl Components::Home`.


module Components::Home
  sig { params(args: T.untyped, kwargs: T.untyped, block: T.untyped).returns(T.untyped) }
  def Article(*args, **kwargs, &block); end

  sig { params(args: T.untyped, kwargs: T.untyped, block: T.untyped).returns(T.untyped) }
  def Feature(*args, **kwargs, &block); end

  class << self
    sig { params(args: T.untyped, kwargs: T.untyped, block: T.untyped).returns(T.untyped) }
    def Article(*args, **kwargs, &block); end

    sig { params(args: T.untyped, kwargs: T.untyped, block: T.untyped).returns(T.untyped) }
    def Feature(*args, **kwargs, &block); end
  end
end

class Components::Home::Article
  include Components::Home
end

class Components::Home::Feature
  include Components::Home
end
