# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Components::Likes`.
# Please instead update this file by running `bin/tapioca dsl Components::Likes`.


module Components::Likes
  sig { params(args: T.untyped, kwargs: T.untyped, block: T.untyped).returns(T.untyped) }
  def Button(*args, **kwargs, &block); end

  class << self
    sig { params(args: T.untyped, kwargs: T.untyped, block: T.untyped).returns(T.untyped) }
    def Button(*args, **kwargs, &block); end
  end
end

class Components::Likes::Button
  include Components::Likes
end
