# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Components::OauthButton`.
# Please instead update this file by running `bin/tapioca dsl Components::OauthButton`.


module Components::OauthButton
  sig { params(args: T.untyped, kwargs: T.untyped, block: T.untyped).returns(T.untyped) }
  def Apple(*args, **kwargs, &block); end

  sig { params(args: T.untyped, kwargs: T.untyped, block: T.untyped).returns(T.untyped) }
  def Github(*args, **kwargs, &block); end

  sig { params(args: T.untyped, kwargs: T.untyped, block: T.untyped).returns(T.untyped) }
  def Google(*args, **kwargs, &block); end

  class << self
    sig { params(args: T.untyped, kwargs: T.untyped, block: T.untyped).returns(T.untyped) }
    def Apple(*args, **kwargs, &block); end

    sig { params(args: T.untyped, kwargs: T.untyped, block: T.untyped).returns(T.untyped) }
    def Github(*args, **kwargs, &block); end

    sig { params(args: T.untyped, kwargs: T.untyped, block: T.untyped).returns(T.untyped) }
    def Google(*args, **kwargs, &block); end
  end
end

class Components::OauthButton::Apple
  include Components::OauthButton
end

class Components::OauthButton::Github
  include Components::OauthButton
end

class Components::OauthButton::Google
  include Components::OauthButton
end
