# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ArticlePresentable`.
# Please instead update this file by running `bin/tapioca dsl ArticlePresentable`.


module ArticlePresentable
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods

  module GeneratedClassMethods
    def default_url_options; end
    def default_url_options=(value); end
    def default_url_options?; end
  end

  module GeneratedInstanceMethods
    def default_url_options; end
    def default_url_options=(value); end
    def default_url_options?; end
  end
end
