# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DiscardedArticleCleanupJob`.
# Please instead update this file by running `bin/tapioca dsl DiscardedArticleCleanupJob`.


class DiscardedArticleCleanupJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: DiscardedArticleCleanupJob).void)
      ).returns(T.any(DiscardedArticleCleanupJob, FalseClass))
    end
    def perform_later(&block); end

    sig { void }
    def perform_now; end
  end
end
