# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `FedipubLikeable`.
# Please instead update this file by running `bin/tapioca dsl FedipubLikeable`.


module FedipubLikeable
  mixes_in_class_methods ::Fedipub::HandlesSocialActivities::ClassMethods
end
