# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `IndexNowJob`.
# Please instead update this file by running `bin/tapioca dsl IndexNowJob`.


class IndexNowJob
  class << self
    sig do
      params(
        article_id: ::Integer,
        block: T.nilable(T.proc.params(job: IndexNowJob).void)
      ).returns(T.any(IndexNowJob, FalseClass))
    end
    def perform_later(article_id, &block); end

    sig { params(article_id: ::Integer).void }
    def perform_now(article_id); end
  end
end
