# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RssSitePageJob`.
# Please instead update this file by running `bin/tapioca dsl RssSitePageJob`.


class RssSitePageJob
  class << self
    sig do
      params(
        ids: T::Array[::Integer],
        block: T.nilable(T.proc.params(job: RssSitePageJob).void)
      ).returns(T.any(RssSitePageJob, FalseClass))
    end
    def perform_later(ids, &block); end

    sig { params(ids: T::Array[::Integer]).void }
    def perform_now(ids); end
  end
end
