# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SlackArticlePresenter`.
# Please instead update this file by running `bin/tapioca dsl SlackArticlePresenter`.


class SlackArticlePresenter
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
