# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserSerializer`.
# Please instead update this file by running `bin/tapioca dsl UserSerializer`.


class UserSerializer
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
