# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RailsAiContext::McpController`.
# Please instead update this file by running `bin/tapioca dsl RailsAiContext::McpController`.


class RailsAiContext::McpController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
