# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PgQuery::BoolTestType`.
# Please instead update this file by running `bin/tapioca dsl PgQuery::BoolTestType`.


module PgQuery::BoolTestType
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

PgQuery::BoolTestType::BOOL_TEST_TYPE_UNDEFINED = 0
PgQuery::BoolTestType::IS_FALSE = 3
PgQuery::BoolTestType::IS_NOT_FALSE = 4
PgQuery::BoolTestType::IS_NOT_TRUE = 2
PgQuery::BoolTestType::IS_NOT_UNKNOWN = 6
PgQuery::BoolTestType::IS_TRUE = 1
PgQuery::BoolTestType::IS_UNKNOWN = 5
