# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PgQuery::Integer`.
# Please instead update this file by running `bin/tapioca dsl PgQuery::Integer`.


class PgQuery::Integer < Google::Protobuf::AbstractMessage
  sig { params(ival: T.nilable(Integer)).void }
  def initialize(ival: nil); end

  sig { void }
  def clear_ival; end

  sig { returns(Integer) }
  def ival; end

  sig { params(value: Integer).void }
  def ival=(value); end
end
