# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PgQuery::SinglePartitionSpec`.
# Please instead update this file by running `bin/tapioca dsl PgQuery::SinglePartitionSpec`.


class PgQuery::SinglePartitionSpec < Google::Protobuf::AbstractMessage
  sig { void }
  def initialize; end
end
