# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MissionControl::Jobs::JobsController::HelperMethods`.
# Please instead update this file by running `bin/tapioca dsl MissionControl::Jobs::JobsController::HelperMethods`.


module MissionControl::Jobs::JobsController::HelperMethods
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
