# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fedipub::DataEntity`.
# Please instead update this file by running `bin/tapioca dsl Fedipub::DataEntity`.


module Fedipub::DataEntity
  mixes_in_class_methods ::Fedipub::HandlesDeleteRequests::ClassMethods
  mixes_in_class_methods ::Fedipub::HandlesSocialActivities::ClassMethods
end
