# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fedipub::NotifyInboxJob`.
# Please instead update this file by running `bin/tapioca dsl Fedipub::NotifyInboxJob`.


class Fedipub::NotifyInboxJob
  class << self
    sig do
      params(
        activity: T.untyped,
        inbox_url: T.untyped,
        block: T.nilable(T.proc.params(job: Fedipub::NotifyInboxJob).void)
      ).returns(T.any(Fedipub::NotifyInboxJob, FalseClass))
    end
    def perform_later(activity, inbox_url = T.unsafe(nil), &block); end

    sig { params(activity: T.untyped, inbox_url: T.untyped).returns(T.untyped) }
    def perform_now(activity, inbox_url = T.unsafe(nil)); end
  end
end
