# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Madmin::ApplicationHelper`.
# Please instead update this file by running `bin/tapioca dsl Madmin::ApplicationHelper`.


module Madmin::ApplicationHelper
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
