# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Madmin::ResourceController`.
# Please instead update this file by running `bin/tapioca dsl Madmin::ResourceController`.


class Madmin::ResourceController
  sig { returns(HelperProxy) }
  def helpers; end

  module HelperMethods
    include ::Turbo::DriveHelper
    include ::Turbo::FramesHelper
    include ::Turbo::IncludesHelper
    include ::Turbo::StreamsHelper
    include ::ActionView::Helpers::CaptureHelper
    include ::ActionView::Helpers::OutputSafetyHelper
    include ::ActionView::Helpers::TagHelper
    include ::Turbo::Streams::ActionHelper
    include ::ActionText::ContentHelper
    include ::ActionText::TagHelper
    include ::Lexxy::TagHelper
    include ::Importmap::ImportmapTagsHelper
    include ::DeviseI18n::ViewHelpers
    include ::ActionController::Base::HelperMethods
    include ::ActionDispatch::Routing::PolymorphicRoutes
    include ::ActionDispatch::Routing::UrlFor
    include ::GeneratedUrlHelpersModule
    include ::GeneratedPathHelpersModule
    include ::Madmin::ApplicationHelper
    include ::Madmin::NavHelper
    include ::Madmin::SortHelper
    include ::Madmin::BaseController::HelperMethods

    sig { returns(T.untyped) }
    def resource; end
  end

  class HelperProxy < ::ActionView::Base
    include HelperMethods
  end
end
