# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RubyLLM::Monitoring::ApplicationController`.
# Please instead update this file by running `bin/tapioca dsl RubyLLM::Monitoring::ApplicationController`.


class RubyLLM::Monitoring::ApplicationController
  sig { returns(HelperProxy) }
  def helpers; end

  module HelperMethods
    include ::Turbo::DriveHelper
    include ::Turbo::FramesHelper
    include ::Turbo::IncludesHelper
    include ::Turbo::StreamsHelper
    include ::ActionView::Helpers::CaptureHelper
    include ::ActionView::Helpers::OutputSafetyHelper
    include ::ActionView::Helpers::TagHelper
    include ::Turbo::Streams::ActionHelper
    include ::ActionText::ContentHelper
    include ::ActionText::TagHelper
    include ::Lexxy::TagHelper
    include ::Importmap::ImportmapTagsHelper
    include ::DeviseI18n::ViewHelpers
    include ::ActionController::Base::HelperMethods
    include ::RubyLLM::Monitoring::ApplicationHelper
    include ::RubyLLM::Monitoring::AlertsHelper
    include ::RubyLLM::Monitoring::EventsHelper
    include ::RubyLLM::Monitoring::MetricsHelper

    sig { returns(T.untyped) }
    def filter_param; end
  end

  class HelperProxy < ::ActionView::Base
    include HelperMethods
  end
end
